// Copyright 2015 The gRPC Authors
// protoc -I . --go_out=plugins=grpc:. ./warning.proto

// protoc -I ./ --go_out=. ./warning/warning.proto
// protoc -I ./ --go-grpc_out=. warning/warning.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: warning/warning.proto

package warning

import (
	api "github.com/felix-186/api-client-go/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryWarningRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         []byte                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Archive       string                 `protobuf:"bytes,2,opt,name=archive,proto3" json:"archive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryWarningRequest) Reset() {
	*x = QueryWarningRequest{}
	mi := &file_warning_warning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryWarningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryWarningRequest) ProtoMessage() {}

func (x *QueryWarningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warning_warning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryWarningRequest.ProtoReflect.Descriptor instead.
func (*QueryWarningRequest) Descriptor() ([]byte, []int) {
	return file_warning_warning_proto_rawDescGZIP(), []int{0}
}

func (x *QueryWarningRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *QueryWarningRequest) GetArchive() string {
	if x != nil {
		return x.Archive
	}
	return ""
}

type GetOrDeleteWarningRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Archive       string                 `protobuf:"bytes,2,opt,name=archive,proto3" json:"archive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrDeleteWarningRequest) Reset() {
	*x = GetOrDeleteWarningRequest{}
	mi := &file_warning_warning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrDeleteWarningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrDeleteWarningRequest) ProtoMessage() {}

func (x *GetOrDeleteWarningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warning_warning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrDeleteWarningRequest.ProtoReflect.Descriptor instead.
func (*GetOrDeleteWarningRequest) Descriptor() ([]byte, []int) {
	return file_warning_warning_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrDeleteWarningRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetOrDeleteWarningRequest) GetArchive() string {
	if x != nil {
		return x.Archive
	}
	return ""
}

type WarnStatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 传 "table" 时额外返回每张表按级别统计的报警设备数
	Table         string `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarnStatsRequest) Reset() {
	*x = WarnStatsRequest{}
	mi := &file_warning_warning_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarnStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarnStatsRequest) ProtoMessage() {}

func (x *WarnStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warning_warning_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarnStatsRequest.ProtoReflect.Descriptor instead.
func (*WarnStatsRequest) Descriptor() ([]byte, []int) {
	return file_warning_warning_proto_rawDescGZIP(), []int{2}
}

func (x *WarnStatsRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

var File_warning_warning_proto protoreflect.FileDescriptor

const file_warning_warning_proto_rawDesc = "" +
	"\n" +
	"\x15warning/warning.proto\x12\awarning\x1a\rapi/api.proto\"E\n" +
	"\x13QueryWarningRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\fR\x05query\x12\x18\n" +
	"\aarchive\x18\x02 \x01(\tR\aarchive\"E\n" +
	"\x19GetOrDeleteWarningRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aarchive\x18\x02 \x01(\tR\aarchive\"(\n" +
	"\x10WarnStatsRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table2\xa0\x02\n" +
	"\vWarnService\x126\n" +
	"\x05Query\x12\x1c.warning.QueryWarningRequest\x1a\r.api.Response\"\x00\x12:\n" +
	"\x03Get\x12\".warning.GetOrDeleteWarningRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Create\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\vBatchCreate\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x12:\n" +
	"\fGetWarnStats\x12\x19.warning.WarnStatsRequest\x1a\r.api.Response\"\x002\x81\x02\n" +
	"\vRuleService\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\vBatchCreate\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Update\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\x06Delete\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12.\n" +
	"\aReplace\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00BD\n" +
	"'cn.gtsiot.sdk.client.dubbo.grpc.warningP\x01Z\x11./warning;warning\x88\x01\x01\xa0\x01\x01b\x06proto3"

var (
	file_warning_warning_proto_rawDescOnce sync.Once
	file_warning_warning_proto_rawDescData []byte
)

func file_warning_warning_proto_rawDescGZIP() []byte {
	file_warning_warning_proto_rawDescOnce.Do(func() {
		file_warning_warning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_warning_warning_proto_rawDesc), len(file_warning_warning_proto_rawDesc)))
	})
	return file_warning_warning_proto_rawDescData
}

var file_warning_warning_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_warning_warning_proto_goTypes = []any{
	(*QueryWarningRequest)(nil),       // 0: warning.QueryWarningRequest
	(*GetOrDeleteWarningRequest)(nil), // 1: warning.GetOrDeleteWarningRequest
	(*WarnStatsRequest)(nil),          // 2: warning.WarnStatsRequest
	(*api.CreateRequest)(nil),         // 3: api.CreateRequest
	(*api.QueryRequest)(nil),          // 4: api.QueryRequest
	(*api.UpdateRequest)(nil),         // 5: api.UpdateRequest
	(*api.GetOrDeleteRequest)(nil),    // 6: api.GetOrDeleteRequest
	(*api.Response)(nil),              // 7: api.Response
}
var file_warning_warning_proto_depIdxs = []int32{
	0,  // 0: warning.WarnService.Query:input_type -> warning.QueryWarningRequest
	1,  // 1: warning.WarnService.Get:input_type -> warning.GetOrDeleteWarningRequest
	3,  // 2: warning.WarnService.Create:input_type -> api.CreateRequest
	3,  // 3: warning.WarnService.BatchCreate:input_type -> api.CreateRequest
	2,  // 4: warning.WarnService.GetWarnStats:input_type -> warning.WarnStatsRequest
	4,  // 5: warning.RuleService.Query:input_type -> api.QueryRequest
	3,  // 6: warning.RuleService.BatchCreate:input_type -> api.CreateRequest
	5,  // 7: warning.RuleService.Update:input_type -> api.UpdateRequest
	6,  // 8: warning.RuleService.Delete:input_type -> api.GetOrDeleteRequest
	5,  // 9: warning.RuleService.Replace:input_type -> api.UpdateRequest
	7,  // 10: warning.WarnService.Query:output_type -> api.Response
	7,  // 11: warning.WarnService.Get:output_type -> api.Response
	7,  // 12: warning.WarnService.Create:output_type -> api.Response
	7,  // 13: warning.WarnService.BatchCreate:output_type -> api.Response
	7,  // 14: warning.WarnService.GetWarnStats:output_type -> api.Response
	7,  // 15: warning.RuleService.Query:output_type -> api.Response
	7,  // 16: warning.RuleService.BatchCreate:output_type -> api.Response
	7,  // 17: warning.RuleService.Update:output_type -> api.Response
	7,  // 18: warning.RuleService.Delete:output_type -> api.Response
	7,  // 19: warning.RuleService.Replace:output_type -> api.Response
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_warning_warning_proto_init() }
func file_warning_warning_proto_init() {
	if File_warning_warning_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warning_warning_proto_rawDesc), len(file_warning_warning_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_warning_warning_proto_goTypes,
		DependencyIndexes: file_warning_warning_proto_depIdxs,
		MessageInfos:      file_warning_warning_proto_msgTypes,
	}.Build()
	File_warning_warning_proto = out.File
	file_warning_warning_proto_goTypes = nil
	file_warning_warning_proto_depIdxs = nil
}
