// Copyright 2015 The gRPC Authors
// protoc -I ./ --go_out=. ./flow/flow.proto
// protoc -I ./ --go-grpc_out=. flow/flow.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: flow/flow.proto

package flow

import (
	api "github.com/felix-186/api-client-go/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN         HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING         HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING     HealthCheckResponse_ServingStatus = 2
	HealthCheckResponse_SERVICE_UNKNOWN HealthCheckResponse_ServingStatus = 3
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
		3: "SERVICE_UNKNOWN",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":         0,
		"SERVING":         1,
		"NOT_SERVING":     2,
		"SERVICE_UNKNOWN": 3,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_flow_flow_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_flow_flow_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{5, 0}
}

type Error_ErrorCode int32

const (
	Error_Register Error_ErrorCode = 0
)

// Enum value maps for Error_ErrorCode.
var (
	Error_ErrorCode_name = map[int32]string{
		0: "Register",
	}
	Error_ErrorCode_value = map[string]int32{
		"Register": 0,
	}
)

func (x Error_ErrorCode) Enum() *Error_ErrorCode {
	p := new(Error_ErrorCode)
	*p = x
	return p
}

func (x Error_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Error_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_flow_flow_proto_enumTypes[1].Descriptor()
}

func (Error_ErrorCode) Type() protoreflect.EnumType {
	return &file_flow_flow_proto_enumTypes[1]
}

func (x Error_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Error_ErrorCode.Descriptor instead.
func (Error_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{6, 0}
}

type ExtensionHealthCheckResponse_ServingStatus int32

const (
	ExtensionHealthCheckResponse_UNKNOWN         ExtensionHealthCheckResponse_ServingStatus = 0
	ExtensionHealthCheckResponse_SERVING         ExtensionHealthCheckResponse_ServingStatus = 1
	ExtensionHealthCheckResponse_NOT_SERVING     ExtensionHealthCheckResponse_ServingStatus = 2
	ExtensionHealthCheckResponse_SERVICE_UNKNOWN ExtensionHealthCheckResponse_ServingStatus = 3
)

// Enum value maps for ExtensionHealthCheckResponse_ServingStatus.
var (
	ExtensionHealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
		3: "SERVICE_UNKNOWN",
	}
	ExtensionHealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":         0,
		"SERVING":         1,
		"NOT_SERVING":     2,
		"SERVICE_UNKNOWN": 3,
	}
)

func (x ExtensionHealthCheckResponse_ServingStatus) Enum() *ExtensionHealthCheckResponse_ServingStatus {
	p := new(ExtensionHealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x ExtensionHealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExtensionHealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_flow_flow_proto_enumTypes[2].Descriptor()
}

func (ExtensionHealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_flow_flow_proto_enumTypes[2]
}

func (x ExtensionHealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExtensionHealthCheckResponse_ServingStatus.Descriptor instead.
func (ExtensionHealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{12, 0}
}

type ExtensionError_ErrorCode int32

const (
	ExtensionError_Schema ExtensionError_ErrorCode = 0
	ExtensionError_Run    ExtensionError_ErrorCode = 1
)

// Enum value maps for ExtensionError_ErrorCode.
var (
	ExtensionError_ErrorCode_name = map[int32]string{
		0: "Schema",
		1: "Run",
	}
	ExtensionError_ErrorCode_value = map[string]int32{
		"Schema": 0,
		"Run":    1,
	}
)

func (x ExtensionError_ErrorCode) Enum() *ExtensionError_ErrorCode {
	p := new(ExtensionError_ErrorCode)
	*p = x
	return p
}

func (x ExtensionError_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExtensionError_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_flow_flow_proto_enumTypes[3].Descriptor()
}

func (ExtensionError_ErrorCode) Type() protoreflect.EnumType {
	return &file_flow_flow_proto_enumTypes[3]
}

func (x ExtensionError_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExtensionError_ErrorCode.Descriptor instead.
func (ExtensionError_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{13, 0}
}

type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	Config        string                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Element       []byte                 `protobuf:"bytes,3,opt,name=element,proto3" json:"element,omitempty"`
	Variables     []byte                 `protobuf:"bytes,4,opt,name=variables,proto3" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_flow_flow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flow_flow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *RunRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *RunRequest) GetElement() []byte {
	if x != nil {
		return x.Element
	}
	return nil
}

func (x *RunRequest) GetVariables() []byte {
	if x != nil {
		return x.Variables
	}
	return nil
}

type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           string                 `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_flow_flow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flow_flow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{1}
}

func (x *RunResponse) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

type ResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=jobId,proto3" json:"jobId,omitempty"`
	ElementId     string                 `protobuf:"bytes,3,opt,name=elementId,proto3" json:"elementId,omitempty"`
	Variables     []byte                 `protobuf:"bytes,4,opt,name=variables,proto3" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRequest) Reset() {
	*x = ResumeRequest{}
	mi := &file_flow_flow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRequest) ProtoMessage() {}

func (x *ResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flow_flow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRequest) Descriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{2}
}

func (x *ResumeRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ResumeRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ResumeRequest) GetElementId() string {
	if x != nil {
		return x.ElementId
	}
	return ""
}

func (x *ResumeRequest) GetVariables() []byte {
	if x != nil {
		return x.Variables
	}
	return nil
}

type FailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=jobId,proto3" json:"jobId,omitempty"`
	ElementId     string                 `protobuf:"bytes,3,opt,name=elementId,proto3" json:"elementId,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailRequest) Reset() {
	*x = FailRequest{}
	mi := &file_flow_flow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailRequest) ProtoMessage() {}

func (x *FailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flow_flow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailRequest.ProtoReflect.Descriptor instead.
func (*FailRequest) Descriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{3}
}

func (x *FailRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *FailRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *FailRequest) GetElementId() string {
	if x != nil {
		return x.ElementId
	}
	return ""
}

func (x *FailRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_flow_flow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flow_flow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{4}
}

func (x *HealthCheckRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=flow.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	Errors        []*Error                          `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_flow_flow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flow_flow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *HealthCheckResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Error_ErrorCode        `protobuf:"varint,1,opt,name=code,proto3,enum=flow.Error_ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_flow_flow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_flow_flow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetCode() Error_ErrorCode {
	if x != nil {
		return x.Code
	}
	return Error_Register
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	FlowId        string                 `protobuf:"bytes,2,opt,name=flowId,proto3" json:"flowId,omitempty"`
	Job           string                 `protobuf:"bytes,3,opt,name=job,proto3" json:"job,omitempty"`
	ElementId     string                 `protobuf:"bytes,4,opt,name=elementId,proto3" json:"elementId,omitempty"`
	ElementJob    string                 `protobuf:"bytes,5,opt,name=elementJob,proto3" json:"elementJob,omitempty"`
	Config        []byte                 `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowRequest) Reset() {
	*x = FlowRequest{}
	mi := &file_flow_flow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowRequest) ProtoMessage() {}

func (x *FlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flow_flow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowRequest.ProtoReflect.Descriptor instead.
func (*FlowRequest) Descriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{7}
}

func (x *FlowRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *FlowRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *FlowRequest) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *FlowRequest) GetElementId() string {
	if x != nil {
		return x.ElementId
	}
	return ""
}

func (x *FlowRequest) GetElementJob() string {
	if x != nil {
		return x.ElementJob
	}
	return ""
}

func (x *FlowRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

type FlowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ElementJob    string                 `protobuf:"bytes,1,opt,name=elementJob,proto3" json:"elementJob,omitempty"`
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Info          string                 `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	Result        []byte                 `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowResponse) Reset() {
	*x = FlowResponse{}
	mi := &file_flow_flow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowResponse) ProtoMessage() {}

func (x *FlowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flow_flow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowResponse.ProtoReflect.Descriptor instead.
func (*FlowResponse) Descriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{8}
}

func (x *FlowResponse) GetElementJob() string {
	if x != nil {
		return x.ElementJob
	}
	return ""
}

func (x *FlowResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *FlowResponse) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *FlowResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *FlowResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type DebugRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	FlowId        string                 `protobuf:"bytes,2,opt,name=flowId,proto3" json:"flowId,omitempty"`
	ElementId     string                 `protobuf:"bytes,3,opt,name=elementId,proto3" json:"elementId,omitempty"`
	ElementJob    string                 `protobuf:"bytes,5,opt,name=elementJob,proto3" json:"elementJob,omitempty"`
	Config        []byte                 `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugRequest) Reset() {
	*x = DebugRequest{}
	mi := &file_flow_flow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugRequest) ProtoMessage() {}

func (x *DebugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flow_flow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugRequest.ProtoReflect.Descriptor instead.
func (*DebugRequest) Descriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{9}
}

func (x *DebugRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DebugRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *DebugRequest) GetElementId() string {
	if x != nil {
		return x.ElementId
	}
	return ""
}

func (x *DebugRequest) GetElementJob() string {
	if x != nil {
		return x.ElementJob
	}
	return ""
}

func (x *DebugRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

type DebugResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ElementJob    string                 `protobuf:"bytes,1,opt,name=elementJob,proto3" json:"elementJob,omitempty"`
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Info          string                 `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	Result        []byte                 `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugResponse) Reset() {
	*x = DebugResponse{}
	mi := &file_flow_flow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugResponse) ProtoMessage() {}

func (x *DebugResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flow_flow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugResponse.ProtoReflect.Descriptor instead.
func (*DebugResponse) Descriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{10}
}

func (x *DebugResponse) GetElementJob() string {
	if x != nil {
		return x.ElementJob
	}
	return ""
}

func (x *DebugResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *DebugResponse) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *DebugResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *DebugResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type ExtensionHealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionHealthCheckRequest) Reset() {
	*x = ExtensionHealthCheckRequest{}
	mi := &file_flow_flow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionHealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionHealthCheckRequest) ProtoMessage() {}

func (x *ExtensionHealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flow_flow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionHealthCheckRequest.ProtoReflect.Descriptor instead.
func (*ExtensionHealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{11}
}

func (x *ExtensionHealthCheckRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ExtensionHealthCheckResponse struct {
	state         protoimpl.MessageState                     `protogen:"open.v1"`
	Status        ExtensionHealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=flow.ExtensionHealthCheckResponse_ServingStatus" json:"status,omitempty"`
	Errors        []*ExtensionError                          `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionHealthCheckResponse) Reset() {
	*x = ExtensionHealthCheckResponse{}
	mi := &file_flow_flow_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionHealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionHealthCheckResponse) ProtoMessage() {}

func (x *ExtensionHealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flow_flow_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionHealthCheckResponse.ProtoReflect.Descriptor instead.
func (*ExtensionHealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{12}
}

func (x *ExtensionHealthCheckResponse) GetStatus() ExtensionHealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return ExtensionHealthCheckResponse_UNKNOWN
}

func (x *ExtensionHealthCheckResponse) GetErrors() []*ExtensionError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ExtensionError struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Code          ExtensionError_ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=flow.ExtensionError_ErrorCode" json:"code,omitempty"`
	Message       string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionError) Reset() {
	*x = ExtensionError{}
	mi := &file_flow_flow_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionError) ProtoMessage() {}

func (x *ExtensionError) ProtoReflect() protoreflect.Message {
	mi := &file_flow_flow_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionError.ProtoReflect.Descriptor instead.
func (*ExtensionError) Descriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{13}
}

func (x *ExtensionError) GetCode() ExtensionError_ErrorCode {
	if x != nil {
		return x.Code
	}
	return ExtensionError_Schema
}

func (x *ExtensionError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ExtensionSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       string                 `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Locale        string                 `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionSchemaRequest) Reset() {
	*x = ExtensionSchemaRequest{}
	mi := &file_flow_flow_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionSchemaRequest) ProtoMessage() {}

func (x *ExtensionSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flow_flow_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionSchemaRequest.ProtoReflect.Descriptor instead.
func (*ExtensionSchemaRequest) Descriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{14}
}

func (x *ExtensionSchemaRequest) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *ExtensionSchemaRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type ExtensionRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       string                 `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionRunRequest) Reset() {
	*x = ExtensionRunRequest{}
	mi := &file_flow_flow_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionRunRequest) ProtoMessage() {}

func (x *ExtensionRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flow_flow_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionRunRequest.ProtoReflect.Descriptor instead.
func (*ExtensionRunRequest) Descriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{15}
}

func (x *ExtensionRunRequest) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *ExtensionRunRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExtensionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       string                 `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Info          string                 `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	Result        []byte                 `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionResult) Reset() {
	*x = ExtensionResult{}
	mi := &file_flow_flow_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionResult) ProtoMessage() {}

func (x *ExtensionResult) ProtoReflect() protoreflect.Message {
	mi := &file_flow_flow_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionResult.ProtoReflect.Descriptor instead.
func (*ExtensionResult) Descriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{16}
}

func (x *ExtensionResult) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *ExtensionResult) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *ExtensionResult) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *ExtensionResult) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ExtensionResult) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_flow_flow_proto protoreflect.FileDescriptor

const file_flow_flow_proto_rawDesc = "" +
	"\n" +
	"\x0fflow/flow.proto\x12\x04flow\x1a\rapi/api.proto\x1a\x1bgoogle/protobuf/empty.proto\"z\n" +
	"\n" +
	"RunRequest\x12\x1c\n" +
	"\tprojectId\x18\x01 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06config\x18\x02 \x01(\tR\x06config\x12\x18\n" +
	"\aelement\x18\x03 \x01(\fR\aelement\x12\x1c\n" +
	"\tvariables\x18\x04 \x01(\fR\tvariables\"\x1f\n" +
	"\vRunResponse\x12\x10\n" +
	"\x03job\x18\x01 \x01(\tR\x03job\"\x7f\n" +
	"\rResumeRequest\x12\x1c\n" +
	"\tprojectId\x18\x01 \x01(\tR\tprojectId\x12\x14\n" +
	"\x05jobId\x18\x02 \x01(\tR\x05jobId\x12\x1c\n" +
	"\telementId\x18\x03 \x01(\tR\telementId\x12\x1c\n" +
	"\tvariables\x18\x04 \x01(\fR\tvariables\"\x83\x01\n" +
	"\vFailRequest\x12\x1c\n" +
	"\tprojectId\x18\x01 \x01(\tR\tprojectId\x12\x14\n" +
	"\x05jobId\x18\x02 \x01(\tR\x05jobId\x12\x1c\n" +
	"\telementId\x18\x03 \x01(\tR\telementId\x12\"\n" +
	"\ferrorMessage\x18\x04 \x01(\tR\ferrorMessage\"(\n" +
	"\x12HealthCheckRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xcc\x01\n" +
	"\x13HealthCheckResponse\x12?\n" +
	"\x06status\x18\x01 \x01(\x0e2'.flow.HealthCheckResponse.ServingStatusR\x06status\x12#\n" +
	"\x06errors\x18\x02 \x03(\v2\v.flow.ErrorR\x06errors\"O\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\x12\x13\n" +
	"\x0fSERVICE_UNKNOWN\x10\x03\"g\n" +
	"\x05Error\x12)\n" +
	"\x04code\x18\x01 \x01(\x0e2\x15.flow.Error.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x19\n" +
	"\tErrorCode\x12\f\n" +
	"\bRegister\x10\x00\"\xab\x01\n" +
	"\vFlowRequest\x12\x1c\n" +
	"\tprojectId\x18\x01 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06flowId\x18\x02 \x01(\tR\x06flowId\x12\x10\n" +
	"\x03job\x18\x03 \x01(\tR\x03job\x12\x1c\n" +
	"\telementId\x18\x04 \x01(\tR\telementId\x12\x1e\n" +
	"\n" +
	"elementJob\x18\x05 \x01(\tR\n" +
	"elementJob\x12\x16\n" +
	"\x06config\x18\x06 \x01(\fR\x06config\"\x8a\x01\n" +
	"\fFlowResponse\x12\x1e\n" +
	"\n" +
	"elementJob\x18\x01 \x01(\tR\n" +
	"elementJob\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\x12\x12\n" +
	"\x04info\x18\x03 \x01(\tR\x04info\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x16\n" +
	"\x06result\x18\x05 \x01(\fR\x06result\"\x9a\x01\n" +
	"\fDebugRequest\x12\x1c\n" +
	"\tprojectId\x18\x01 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06flowId\x18\x02 \x01(\tR\x06flowId\x12\x1c\n" +
	"\telementId\x18\x03 \x01(\tR\telementId\x12\x1e\n" +
	"\n" +
	"elementJob\x18\x05 \x01(\tR\n" +
	"elementJob\x12\x16\n" +
	"\x06config\x18\x06 \x01(\fR\x06config\"\x8b\x01\n" +
	"\rDebugResponse\x12\x1e\n" +
	"\n" +
	"elementJob\x18\x01 \x01(\tR\n" +
	"elementJob\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\x12\x12\n" +
	"\x04info\x18\x03 \x01(\tR\x04info\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x16\n" +
	"\x06result\x18\x05 \x01(\fR\x06result\"-\n" +
	"\x1bExtensionHealthCheckRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xe7\x01\n" +
	"\x1cExtensionHealthCheckResponse\x12H\n" +
	"\x06status\x18\x01 \x01(\x0e20.flow.ExtensionHealthCheckResponse.ServingStatusR\x06status\x12,\n" +
	"\x06errors\x18\x02 \x03(\v2\x14.flow.ExtensionErrorR\x06errors\"O\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\x12\x13\n" +
	"\x0fSERVICE_UNKNOWN\x10\x03\"\x80\x01\n" +
	"\x0eExtensionError\x122\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1e.flow.ExtensionError.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\" \n" +
	"\tErrorCode\x12\n" +
	"\n" +
	"\x06Schema\x10\x00\x12\a\n" +
	"\x03Run\x10\x01\"J\n" +
	"\x16ExtensionSchemaRequest\x12\x18\n" +
	"\arequest\x18\x01 \x01(\tR\arequest\x12\x16\n" +
	"\x06locale\x18\x02 \x01(\tR\x06locale\"C\n" +
	"\x13ExtensionRunRequest\x12\x18\n" +
	"\arequest\x18\x01 \x01(\tR\arequest\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x87\x01\n" +
	"\x0fExtensionResult\x12\x18\n" +
	"\arequest\x18\x01 \x01(\tR\arequest\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\x12\x12\n" +
	"\x04info\x18\x03 \x01(\tR\x04info\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x16\n" +
	"\x06result\x18\x05 \x01(\fR\x06result2\xce\x03\n" +
	"\x0fFlowTaskService\x12-\n" +
	"\x06Create\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\vBatchCreate\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Update\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x123\n" +
	"\fRevertCreate\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\x06Delete\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12.\n" +
	"\aReplace\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\fUpdateFilter\x12\x11.api.UpdateFilter\x1a\r.api.Response\"\x002\xb2\x02\n" +
	"\vFlowService\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Update\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\vBatchCreate\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\x06Delete\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12.\n" +
	"\aReplace\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x002I\n" +
	"\x18FlowTriggerRecordService\x12-\n" +
	"\x06Create\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x002\x9d\x02\n" +
	"\rEngineService\x12,\n" +
	"\x03Run\x12\x10.flow.RunRequest\x1a\x11.flow.RunResponse\"\x00\x127\n" +
	"\x06Resume\x12\x13.flow.ResumeRequest\x1a\x16.google.protobuf.Empty\"\x00\x127\n" +
	"\x06Revert\x12\x13.flow.ResumeRequest\x1a\x16.google.protobuf.Empty\"\x00\x127\n" +
	"\x06Recall\x12\x13.flow.ResumeRequest\x1a\x16.google.protobuf.Empty\"\x00\x123\n" +
	"\x04Fail\x12\x11.flow.FailRequest\x1a\x16.google.protobuf.Empty\"\x002\xcc\x01\n" +
	"\rPluginService\x12D\n" +
	"\vHealthCheck\x12\x18.flow.HealthCheckRequest\x1a\x19.flow.HealthCheckResponse\"\x00\x127\n" +
	"\bRegister\x12\x12.flow.FlowResponse\x1a\x11.flow.FlowRequest\"\x00(\x010\x01\x12<\n" +
	"\vDebugStream\x12\x13.flow.DebugResponse\x1a\x12.flow.DebugRequest\"\x00(\x010\x012\xfa\x01\n" +
	"\x10ExtensionService\x12V\n" +
	"\vHealthCheck\x12!.flow.ExtensionHealthCheckRequest\x1a\".flow.ExtensionHealthCheckResponse\"\x00\x12I\n" +
	"\fSchemaStream\x12\x15.flow.ExtensionResult\x1a\x1c.flow.ExtensionSchemaRequest\"\x00(\x010\x01\x12C\n" +
	"\tRunStream\x12\x15.flow.ExtensionResult\x1a\x19.flow.ExtensionRunRequest\"\x00(\x010\x012\x99\x03\n" +
	"\x12FlowJobCronService\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\x06Delete\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Update\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12.\n" +
	"\aReplace\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Create\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x121\n" +
	"\n" +
	"CreateMany\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x120\n" +
	"\n" +
	"DeleteMany\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x002\xe9\x02\n" +
	"\x12FlowLogCronService\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\x06Delete\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Update\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Create\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x121\n" +
	"\n" +
	"CreateMany\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x120\n" +
	"\n" +
	"DeleteMany\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00B;\n" +
	"$cn.gtsiot.sdk.client.dubbo.grpc.flowP\x01Z\v./flow;flow\x88\x01\x01\xa0\x01\x01b\x06proto3"

var (
	file_flow_flow_proto_rawDescOnce sync.Once
	file_flow_flow_proto_rawDescData []byte
)

func file_flow_flow_proto_rawDescGZIP() []byte {
	file_flow_flow_proto_rawDescOnce.Do(func() {
		file_flow_flow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flow_flow_proto_rawDesc), len(file_flow_flow_proto_rawDesc)))
	})
	return file_flow_flow_proto_rawDescData
}

var file_flow_flow_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_flow_flow_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_flow_flow_proto_goTypes = []any{
	(HealthCheckResponse_ServingStatus)(0),          // 0: flow.HealthCheckResponse.ServingStatus
	(Error_ErrorCode)(0),                            // 1: flow.Error.ErrorCode
	(ExtensionHealthCheckResponse_ServingStatus)(0), // 2: flow.ExtensionHealthCheckResponse.ServingStatus
	(ExtensionError_ErrorCode)(0),                   // 3: flow.ExtensionError.ErrorCode
	(*RunRequest)(nil),                              // 4: flow.RunRequest
	(*RunResponse)(nil),                             // 5: flow.RunResponse
	(*ResumeRequest)(nil),                           // 6: flow.ResumeRequest
	(*FailRequest)(nil),                             // 7: flow.FailRequest
	(*HealthCheckRequest)(nil),                      // 8: flow.HealthCheckRequest
	(*HealthCheckResponse)(nil),                     // 9: flow.HealthCheckResponse
	(*Error)(nil),                                   // 10: flow.Error
	(*FlowRequest)(nil),                             // 11: flow.FlowRequest
	(*FlowResponse)(nil),                            // 12: flow.FlowResponse
	(*DebugRequest)(nil),                            // 13: flow.DebugRequest
	(*DebugResponse)(nil),                           // 14: flow.DebugResponse
	(*ExtensionHealthCheckRequest)(nil),             // 15: flow.ExtensionHealthCheckRequest
	(*ExtensionHealthCheckResponse)(nil),            // 16: flow.ExtensionHealthCheckResponse
	(*ExtensionError)(nil),                          // 17: flow.ExtensionError
	(*ExtensionSchemaRequest)(nil),                  // 18: flow.ExtensionSchemaRequest
	(*ExtensionRunRequest)(nil),                     // 19: flow.ExtensionRunRequest
	(*ExtensionResult)(nil),                         // 20: flow.ExtensionResult
	(*api.CreateRequest)(nil),                       // 21: api.CreateRequest
	(*api.GetOrDeleteRequest)(nil),                  // 22: api.GetOrDeleteRequest
	(*api.QueryRequest)(nil),                        // 23: api.QueryRequest
	(*api.UpdateRequest)(nil),                       // 24: api.UpdateRequest
	(*api.UpdateFilter)(nil),                        // 25: api.UpdateFilter
	(*api.Response)(nil),                            // 26: api.Response
	(*emptypb.Empty)(nil),                           // 27: google.protobuf.Empty
}
var file_flow_flow_proto_depIdxs = []int32{
	0,  // 0: flow.HealthCheckResponse.status:type_name -> flow.HealthCheckResponse.ServingStatus
	10, // 1: flow.HealthCheckResponse.errors:type_name -> flow.Error
	1,  // 2: flow.Error.code:type_name -> flow.Error.ErrorCode
	2,  // 3: flow.ExtensionHealthCheckResponse.status:type_name -> flow.ExtensionHealthCheckResponse.ServingStatus
	17, // 4: flow.ExtensionHealthCheckResponse.errors:type_name -> flow.ExtensionError
	3,  // 5: flow.ExtensionError.code:type_name -> flow.ExtensionError.ErrorCode
	21, // 6: flow.FlowTaskService.Create:input_type -> api.CreateRequest
	22, // 7: flow.FlowTaskService.Get:input_type -> api.GetOrDeleteRequest
	23, // 8: flow.FlowTaskService.Query:input_type -> api.QueryRequest
	21, // 9: flow.FlowTaskService.BatchCreate:input_type -> api.CreateRequest
	24, // 10: flow.FlowTaskService.Update:input_type -> api.UpdateRequest
	21, // 11: flow.FlowTaskService.RevertCreate:input_type -> api.CreateRequest
	22, // 12: flow.FlowTaskService.Delete:input_type -> api.GetOrDeleteRequest
	24, // 13: flow.FlowTaskService.Replace:input_type -> api.UpdateRequest
	25, // 14: flow.FlowTaskService.UpdateFilter:input_type -> api.UpdateFilter
	23, // 15: flow.FlowService.Query:input_type -> api.QueryRequest
	22, // 16: flow.FlowService.Get:input_type -> api.GetOrDeleteRequest
	24, // 17: flow.FlowService.Update:input_type -> api.UpdateRequest
	21, // 18: flow.FlowService.BatchCreate:input_type -> api.CreateRequest
	22, // 19: flow.FlowService.Delete:input_type -> api.GetOrDeleteRequest
	24, // 20: flow.FlowService.Replace:input_type -> api.UpdateRequest
	21, // 21: flow.FlowTriggerRecordService.Create:input_type -> api.CreateRequest
	4,  // 22: flow.EngineService.Run:input_type -> flow.RunRequest
	6,  // 23: flow.EngineService.Resume:input_type -> flow.ResumeRequest
	6,  // 24: flow.EngineService.Revert:input_type -> flow.ResumeRequest
	6,  // 25: flow.EngineService.Recall:input_type -> flow.ResumeRequest
	7,  // 26: flow.EngineService.Fail:input_type -> flow.FailRequest
	8,  // 27: flow.PluginService.HealthCheck:input_type -> flow.HealthCheckRequest
	12, // 28: flow.PluginService.Register:input_type -> flow.FlowResponse
	14, // 29: flow.PluginService.DebugStream:input_type -> flow.DebugResponse
	15, // 30: flow.ExtensionService.HealthCheck:input_type -> flow.ExtensionHealthCheckRequest
	20, // 31: flow.ExtensionService.SchemaStream:input_type -> flow.ExtensionResult
	20, // 32: flow.ExtensionService.RunStream:input_type -> flow.ExtensionResult
	23, // 33: flow.FlowJobCronService.Query:input_type -> api.QueryRequest
	22, // 34: flow.FlowJobCronService.Get:input_type -> api.GetOrDeleteRequest
	22, // 35: flow.FlowJobCronService.Delete:input_type -> api.GetOrDeleteRequest
	24, // 36: flow.FlowJobCronService.Update:input_type -> api.UpdateRequest
	24, // 37: flow.FlowJobCronService.Replace:input_type -> api.UpdateRequest
	21, // 38: flow.FlowJobCronService.Create:input_type -> api.CreateRequest
	21, // 39: flow.FlowJobCronService.CreateMany:input_type -> api.CreateRequest
	23, // 40: flow.FlowJobCronService.DeleteMany:input_type -> api.QueryRequest
	23, // 41: flow.FlowLogCronService.Query:input_type -> api.QueryRequest
	22, // 42: flow.FlowLogCronService.Get:input_type -> api.GetOrDeleteRequest
	22, // 43: flow.FlowLogCronService.Delete:input_type -> api.GetOrDeleteRequest
	24, // 44: flow.FlowLogCronService.Update:input_type -> api.UpdateRequest
	21, // 45: flow.FlowLogCronService.Create:input_type -> api.CreateRequest
	21, // 46: flow.FlowLogCronService.CreateMany:input_type -> api.CreateRequest
	23, // 47: flow.FlowLogCronService.DeleteMany:input_type -> api.QueryRequest
	26, // 48: flow.FlowTaskService.Create:output_type -> api.Response
	26, // 49: flow.FlowTaskService.Get:output_type -> api.Response
	26, // 50: flow.FlowTaskService.Query:output_type -> api.Response
	26, // 51: flow.FlowTaskService.BatchCreate:output_type -> api.Response
	26, // 52: flow.FlowTaskService.Update:output_type -> api.Response
	26, // 53: flow.FlowTaskService.RevertCreate:output_type -> api.Response
	26, // 54: flow.FlowTaskService.Delete:output_type -> api.Response
	26, // 55: flow.FlowTaskService.Replace:output_type -> api.Response
	26, // 56: flow.FlowTaskService.UpdateFilter:output_type -> api.Response
	26, // 57: flow.FlowService.Query:output_type -> api.Response
	26, // 58: flow.FlowService.Get:output_type -> api.Response
	26, // 59: flow.FlowService.Update:output_type -> api.Response
	26, // 60: flow.FlowService.BatchCreate:output_type -> api.Response
	26, // 61: flow.FlowService.Delete:output_type -> api.Response
	26, // 62: flow.FlowService.Replace:output_type -> api.Response
	26, // 63: flow.FlowTriggerRecordService.Create:output_type -> api.Response
	5,  // 64: flow.EngineService.Run:output_type -> flow.RunResponse
	27, // 65: flow.EngineService.Resume:output_type -> google.protobuf.Empty
	27, // 66: flow.EngineService.Revert:output_type -> google.protobuf.Empty
	27, // 67: flow.EngineService.Recall:output_type -> google.protobuf.Empty
	27, // 68: flow.EngineService.Fail:output_type -> google.protobuf.Empty
	9,  // 69: flow.PluginService.HealthCheck:output_type -> flow.HealthCheckResponse
	11, // 70: flow.PluginService.Register:output_type -> flow.FlowRequest
	13, // 71: flow.PluginService.DebugStream:output_type -> flow.DebugRequest
	16, // 72: flow.ExtensionService.HealthCheck:output_type -> flow.ExtensionHealthCheckResponse
	18, // 73: flow.ExtensionService.SchemaStream:output_type -> flow.ExtensionSchemaRequest
	19, // 74: flow.ExtensionService.RunStream:output_type -> flow.ExtensionRunRequest
	26, // 75: flow.FlowJobCronService.Query:output_type -> api.Response
	26, // 76: flow.FlowJobCronService.Get:output_type -> api.Response
	26, // 77: flow.FlowJobCronService.Delete:output_type -> api.Response
	26, // 78: flow.FlowJobCronService.Update:output_type -> api.Response
	26, // 79: flow.FlowJobCronService.Replace:output_type -> api.Response
	26, // 80: flow.FlowJobCronService.Create:output_type -> api.Response
	26, // 81: flow.FlowJobCronService.CreateMany:output_type -> api.Response
	26, // 82: flow.FlowJobCronService.DeleteMany:output_type -> api.Response
	26, // 83: flow.FlowLogCronService.Query:output_type -> api.Response
	26, // 84: flow.FlowLogCronService.Get:output_type -> api.Response
	26, // 85: flow.FlowLogCronService.Delete:output_type -> api.Response
	26, // 86: flow.FlowLogCronService.Update:output_type -> api.Response
	26, // 87: flow.FlowLogCronService.Create:output_type -> api.Response
	26, // 88: flow.FlowLogCronService.CreateMany:output_type -> api.Response
	26, // 89: flow.FlowLogCronService.DeleteMany:output_type -> api.Response
	48, // [48:90] is the sub-list for method output_type
	6,  // [6:48] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_flow_flow_proto_init() }
func file_flow_flow_proto_init() {
	if File_flow_flow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flow_flow_proto_rawDesc), len(file_flow_flow_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   8,
		},
		GoTypes:           file_flow_flow_proto_goTypes,
		DependencyIndexes: file_flow_flow_proto_depIdxs,
		EnumInfos:         file_flow_flow_proto_enumTypes,
		MessageInfos:      file_flow_flow_proto_msgTypes,
	}.Build()
	File_flow_flow_proto = out.File
	file_flow_flow_proto_goTypes = nil
	file_flow_flow_proto_depIdxs = nil
}
