// Copyright 2015 The gRPC Authors
// protoc -I . --go_out=plugins=grpc:. ./spm.proto

// protoc -I ./ --go_out=. ./spm/spm.proto
// protoc -I ./ --go-grpc_out=. spm/spm.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: spm/spm.proto

package spm

import (
	api "github.com/felix-186/api-client-go/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_spm_spm_proto protoreflect.FileDescriptor

const file_spm_spm_proto_rawDesc = "" +
	"\n" +
	"\rspm/spm.proto\x12\x03spm\x1a\rapi/api.proto2=\n" +
	"\vUserService\x12.\n" +
	"\bGetToken\x12\x11.api.TokenRequest\x1a\r.api.Response\"\x002\xe6\x02\n" +
	"\x0eProjectService\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x124\n" +
	"\x0eQueryAvailable\x12\x11.api.EmptyRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\x06Delete\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Update\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12.\n" +
	"\aReplace\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Create\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x002=\n" +
	"\x0eSettingService\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00B8\n" +
	"#cn.gtsiot.sdk.client.dubbo.grpc.spmP\x01Z\t./spm;spm\x88\x01\x01\xa0\x01\x01b\x06proto3"

var file_spm_spm_proto_goTypes = []any{
	(*api.TokenRequest)(nil),       // 0: api.TokenRequest
	(*api.QueryRequest)(nil),       // 1: api.QueryRequest
	(*api.EmptyRequest)(nil),       // 2: api.EmptyRequest
	(*api.GetOrDeleteRequest)(nil), // 3: api.GetOrDeleteRequest
	(*api.UpdateRequest)(nil),      // 4: api.UpdateRequest
	(*api.CreateRequest)(nil),      // 5: api.CreateRequest
	(*api.Response)(nil),           // 6: api.Response
}
var file_spm_spm_proto_depIdxs = []int32{
	0, // 0: spm.UserService.GetToken:input_type -> api.TokenRequest
	1, // 1: spm.ProjectService.Query:input_type -> api.QueryRequest
	2, // 2: spm.ProjectService.QueryAvailable:input_type -> api.EmptyRequest
	3, // 3: spm.ProjectService.Get:input_type -> api.GetOrDeleteRequest
	3, // 4: spm.ProjectService.Delete:input_type -> api.GetOrDeleteRequest
	4, // 5: spm.ProjectService.Update:input_type -> api.UpdateRequest
	4, // 6: spm.ProjectService.Replace:input_type -> api.UpdateRequest
	5, // 7: spm.ProjectService.Create:input_type -> api.CreateRequest
	1, // 8: spm.SettingService.Query:input_type -> api.QueryRequest
	6, // 9: spm.UserService.GetToken:output_type -> api.Response
	6, // 10: spm.ProjectService.Query:output_type -> api.Response
	6, // 11: spm.ProjectService.QueryAvailable:output_type -> api.Response
	6, // 12: spm.ProjectService.Get:output_type -> api.Response
	6, // 13: spm.ProjectService.Delete:output_type -> api.Response
	6, // 14: spm.ProjectService.Update:output_type -> api.Response
	6, // 15: spm.ProjectService.Replace:output_type -> api.Response
	6, // 16: spm.ProjectService.Create:output_type -> api.Response
	6, // 17: spm.SettingService.Query:output_type -> api.Response
	9, // [9:18] is the sub-list for method output_type
	0, // [0:9] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spm_spm_proto_init() }
func file_spm_spm_proto_init() {
	if File_spm_spm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spm_spm_proto_rawDesc), len(file_spm_spm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_spm_spm_proto_goTypes,
		DependencyIndexes: file_spm_spm_proto_depIdxs,
	}.Build()
	File_spm_spm_proto = out.File
	file_spm_spm_proto_goTypes = nil
	file_spm_spm_proto_depIdxs = nil
}
