// Copyright 2015 The gRPC Authors
// protoc -I . --go_out=plugins=grpc:. ./core.proto   不用

// protoc -I ./ --go_out=. ./core/core.proto
// protoc -I ./ --go-grpc_out=. core/core.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: core/core.proto

package core

import (
	api "github.com/felix-186/api-client-go/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizationRevisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationRevisionRequest) Reset() {
	*x = AuthorizationRevisionRequest{}
	mi := &file_core_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationRevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationRevisionRequest) ProtoMessage() {}

func (x *AuthorizationRevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationRevisionRequest.ProtoReflect.Descriptor instead.
func (*AuthorizationRevisionRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{0}
}

type AuthorizationRevisionResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationVersion int64                  `protobuf:"varint,1,opt,name=authorization_version,json=authorizationVersion,proto3" json:"authorization_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AuthorizationRevisionResponse) Reset() {
	*x = AuthorizationRevisionResponse{}
	mi := &file_core_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationRevisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationRevisionResponse) ProtoMessage() {}

func (x *AuthorizationRevisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationRevisionResponse.ProtoReflect.Descriptor instead.
func (*AuthorizationRevisionResponse) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizationRevisionResponse) GetAuthorizationVersion() int64 {
	if x != nil {
		return x.AuthorizationVersion
	}
	return 0
}

type AuthorizationPermissionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PermissionCode string                 `protobuf:"bytes,1,opt,name=permission_code,json=permissionCode,proto3" json:"permission_code,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthorizationPermissionRequest) Reset() {
	*x = AuthorizationPermissionRequest{}
	mi := &file_core_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationPermissionRequest) ProtoMessage() {}

func (x *AuthorizationPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationPermissionRequest.ProtoReflect.Descriptor instead.
func (*AuthorizationPermissionRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizationPermissionRequest) GetPermissionCode() string {
	if x != nil {
		return x.PermissionCode
	}
	return ""
}

type AuthorizationDecision struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Allowed              bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	AuthorizationVersion int64                  `protobuf:"varint,2,opt,name=authorization_version,json=authorizationVersion,proto3" json:"authorization_version,omitempty"`
	Privileged           bool                   `protobuf:"varint,3,opt,name=privileged,proto3" json:"privileged,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AuthorizationDecision) Reset() {
	*x = AuthorizationDecision{}
	mi := &file_core_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationDecision) ProtoMessage() {}

func (x *AuthorizationDecision) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationDecision.ProtoReflect.Descriptor instead.
func (*AuthorizationDecision) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{3}
}

func (x *AuthorizationDecision) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *AuthorizationDecision) GetAuthorizationVersion() int64 {
	if x != nil {
		return x.AuthorizationVersion
	}
	return 0
}

func (x *AuthorizationDecision) GetPrivileged() bool {
	if x != nil {
		return x.Privileged
	}
	return false
}

type AuthorizationResource struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResourceType     string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ParentResourceId string                 `protobuf:"bytes,2,opt,name=parent_resource_id,json=parentResourceId,proto3" json:"parent_resource_id,omitempty"`
	ResourceId       string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Action           string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthorizationResource) Reset() {
	*x = AuthorizationResource{}
	mi := &file_core_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationResource) ProtoMessage() {}

func (x *AuthorizationResource) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationResource.ProtoReflect.Descriptor instead.
func (*AuthorizationResource) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{4}
}

func (x *AuthorizationResource) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *AuthorizationResource) GetParentResourceId() string {
	if x != nil {
		return x.ParentResourceId
	}
	return ""
}

func (x *AuthorizationResource) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *AuthorizationResource) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type BatchResourceAccessRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Resources     []*AuthorizationResource `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResourceAccessRequest) Reset() {
	*x = BatchResourceAccessRequest{}
	mi := &file_core_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResourceAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResourceAccessRequest) ProtoMessage() {}

func (x *BatchResourceAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResourceAccessRequest.ProtoReflect.Descriptor instead.
func (*BatchResourceAccessRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{5}
}

func (x *BatchResourceAccessRequest) GetResources() []*AuthorizationResource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type ResourceAccessDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *AuthorizationResource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Allowed       bool                   `protobuf:"varint,2,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceAccessDecision) Reset() {
	*x = ResourceAccessDecision{}
	mi := &file_core_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceAccessDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceAccessDecision) ProtoMessage() {}

func (x *ResourceAccessDecision) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceAccessDecision.ProtoReflect.Descriptor instead.
func (*ResourceAccessDecision) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{6}
}

func (x *ResourceAccessDecision) GetResource() *AuthorizationResource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ResourceAccessDecision) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

type BatchResourceAccessResponse struct {
	state                protoimpl.MessageState    `protogen:"open.v1"`
	Decisions            []*ResourceAccessDecision `protobuf:"bytes,1,rep,name=decisions,proto3" json:"decisions,omitempty"`
	AuthorizationVersion int64                     `protobuf:"varint,2,opt,name=authorization_version,json=authorizationVersion,proto3" json:"authorization_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BatchResourceAccessResponse) Reset() {
	*x = BatchResourceAccessResponse{}
	mi := &file_core_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResourceAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResourceAccessResponse) ProtoMessage() {}

func (x *BatchResourceAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResourceAccessResponse.ProtoReflect.Descriptor instead.
func (*BatchResourceAccessResponse) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{7}
}

func (x *BatchResourceAccessResponse) GetDecisions() []*ResourceAccessDecision {
	if x != nil {
		return x.Decisions
	}
	return nil
}

func (x *BatchResourceAccessResponse) GetAuthorizationVersion() int64 {
	if x != nil {
		return x.AuthorizationVersion
	}
	return 0
}

type ListAccessibleResourcesRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResourceType     string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ParentResourceId string                 `protobuf:"bytes,2,opt,name=parent_resource_id,json=parentResourceId,proto3" json:"parent_resource_id,omitempty"`
	Action           string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListAccessibleResourcesRequest) Reset() {
	*x = ListAccessibleResourcesRequest{}
	mi := &file_core_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessibleResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessibleResourcesRequest) ProtoMessage() {}

func (x *ListAccessibleResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessibleResourcesRequest.ProtoReflect.Descriptor instead.
func (*ListAccessibleResourcesRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{8}
}

func (x *ListAccessibleResourcesRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ListAccessibleResourcesRequest) GetParentResourceId() string {
	if x != nil {
		return x.ParentResourceId
	}
	return ""
}

func (x *ListAccessibleResourcesRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type ListAccessibleResourcesResponse struct {
	state                protoimpl.MessageState   `protogen:"open.v1"`
	ResourceIds          []string                 `protobuf:"bytes,1,rep,name=resource_ids,json=resourceIds,proto3" json:"resource_ids,omitempty"`
	Unrestricted         bool                     `protobuf:"varint,2,opt,name=unrestricted,proto3" json:"unrestricted,omitempty"`
	AuthorizationVersion int64                    `protobuf:"varint,3,opt,name=authorization_version,json=authorizationVersion,proto3" json:"authorization_version,omitempty"`
	Resources            []*AuthorizationResource `protobuf:"bytes,4,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ListAccessibleResourcesResponse) Reset() {
	*x = ListAccessibleResourcesResponse{}
	mi := &file_core_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessibleResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessibleResourcesResponse) ProtoMessage() {}

func (x *ListAccessibleResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessibleResourcesResponse.ProtoReflect.Descriptor instead.
func (*ListAccessibleResourcesResponse) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{9}
}

func (x *ListAccessibleResourcesResponse) GetResourceIds() []string {
	if x != nil {
		return x.ResourceIds
	}
	return nil
}

func (x *ListAccessibleResourcesResponse) GetUnrestricted() bool {
	if x != nil {
		return x.Unrestricted
	}
	return false
}

func (x *ListAccessibleResourcesResponse) GetAuthorizationVersion() int64 {
	if x != nil {
		return x.AuthorizationVersion
	}
	return 0
}

func (x *ListAccessibleResourcesResponse) GetResources() []*AuthorizationResource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type GetDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceRequest) Reset() {
	*x = GetDeviceRequest{}
	mi := &file_core_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceRequest) ProtoMessage() {}

func (x *GetDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{10}
}

func (x *GetDeviceRequest) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *GetDeviceRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type GetDataDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Table         string                 `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataDeviceRequest) Reset() {
	*x = GetDataDeviceRequest{}
	mi := &file_core_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataDeviceRequest) ProtoMessage() {}

func (x *GetDataDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataDeviceRequest.ProtoReflect.Descriptor instead.
func (*GetDataDeviceRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{11}
}

func (x *GetDataDeviceRequest) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *GetDataDeviceRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GetDataDeviceRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *GetDataDeviceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRequestName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequestName) Reset() {
	*x = GetRequestName{}
	mi := &file_core_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequestName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestName) ProtoMessage() {}

func (x *GetRequestName) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestName.ProtoReflect.Descriptor instead.
func (*GetRequestName) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{12}
}

func (x *GetRequestName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type VerifyAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullKey       string                 `protobuf:"bytes,1,opt,name=fullKey,proto3" json:"fullKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAPIKeyRequest) Reset() {
	*x = VerifyAPIKeyRequest{}
	mi := &file_core_core_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAPIKeyRequest) ProtoMessage() {}

func (x *VerifyAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*VerifyAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{13}
}

func (x *VerifyAPIKeyRequest) GetFullKey() string {
	if x != nil {
		return x.FullKey
	}
	return ""
}

type VerifyAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAPIKeyResponse) Reset() {
	*x = VerifyAPIKeyResponse{}
	mi := &file_core_core_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAPIKeyResponse) ProtoMessage() {}

func (x *VerifyAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*VerifyAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{14}
}

func (x *VerifyAPIKeyResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type QueryDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Query         []byte                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDataRequest) Reset() {
	*x = QueryDataRequest{}
	mi := &file_core_core_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDataRequest) ProtoMessage() {}

func (x *QueryDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDataRequest.ProtoReflect.Descriptor instead.
func (*QueryDataRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{15}
}

func (x *QueryDataRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *QueryDataRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

type GetOrDeleteDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrDeleteDataRequest) Reset() {
	*x = GetOrDeleteDataRequest{}
	mi := &file_core_core_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrDeleteDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrDeleteDataRequest) ProtoMessage() {}

func (x *GetOrDeleteDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrDeleteDataRequest.ProtoReflect.Descriptor instead.
func (*GetOrDeleteDataRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{16}
}

func (x *GetOrDeleteDataRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *GetOrDeleteDataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	CloseRequire  bool                   `protobuf:"varint,4,opt,name=closeRequire,proto3" json:"closeRequire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDataRequest) Reset() {
	*x = UpdateDataRequest{}
	mi := &file_core_core_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataRequest) ProtoMessage() {}

func (x *UpdateDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataRequest.ProtoReflect.Descriptor instead.
func (*UpdateDataRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateDataRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *UpdateDataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateDataRequest) GetCloseRequire() bool {
	if x != nil {
		return x.CloseRequire
	}
	return false
}

type MultiUpdateDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Query         []byte                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	CloseRequire  bool                   `protobuf:"varint,4,opt,name=closeRequire,proto3" json:"closeRequire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiUpdateDataRequest) Reset() {
	*x = MultiUpdateDataRequest{}
	mi := &file_core_core_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiUpdateDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiUpdateDataRequest) ProtoMessage() {}

func (x *MultiUpdateDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiUpdateDataRequest.ProtoReflect.Descriptor instead.
func (*MultiUpdateDataRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{18}
}

func (x *MultiUpdateDataRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *MultiUpdateDataRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *MultiUpdateDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MultiUpdateDataRequest) GetCloseRequire() bool {
	if x != nil {
		return x.CloseRequire
	}
	return false
}

type CreateDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	CloseRequire  bool                   `protobuf:"varint,3,opt,name=closeRequire,proto3" json:"closeRequire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDataRequest) Reset() {
	*x = CreateDataRequest{}
	mi := &file_core_core_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDataRequest) ProtoMessage() {}

func (x *CreateDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDataRequest.ProtoReflect.Descriptor instead.
func (*CreateDataRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{19}
}

func (x *CreateDataRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *CreateDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateDataRequest) GetCloseRequire() bool {
	if x != nil {
		return x.CloseRequire
	}
	return false
}

type LoginUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_core_core_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{20}
}

func (x *LoginUserRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_core_core_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{21}
}

func (x *UploadFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DownloadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileResponse) Reset() {
	*x = DownloadFileResponse{}
	mi := &file_core_core_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileResponse) ProtoMessage() {}

func (x *DownloadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileResponse.ProtoReflect.Descriptor instead.
func (*DownloadFileResponse) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{22}
}

func (x *DownloadFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type MediaLibraryQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Catalog       string                 `protobuf:"bytes,1,opt,name=catalog,proto3" json:"catalog,omitempty"`
	AddBase64     bool                   `protobuf:"varint,2,opt,name=addBase64,proto3" json:"addBase64,omitempty"`
	IsFile        bool                   `protobuf:"varint,3,opt,name=isFile,proto3" json:"isFile,omitempty"`
	Query         []byte                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaLibraryQueryRequest) Reset() {
	*x = MediaLibraryQueryRequest{}
	mi := &file_core_core_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaLibraryQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaLibraryQueryRequest) ProtoMessage() {}

func (x *MediaLibraryQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaLibraryQueryRequest.ProtoReflect.Descriptor instead.
func (*MediaLibraryQueryRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{23}
}

func (x *MediaLibraryQueryRequest) GetCatalog() string {
	if x != nil {
		return x.Catalog
	}
	return ""
}

func (x *MediaLibraryQueryRequest) GetAddBase64() bool {
	if x != nil {
		return x.AddBase64
	}
	return false
}

func (x *MediaLibraryQueryRequest) GetIsFile() bool {
	if x != nil {
		return x.IsFile
	}
	return false
}

func (x *MediaLibraryQueryRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

type MediaLibraryUploadFromUrlRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FileUrl          string                 `protobuf:"bytes,1,opt,name=fileUrl,proto3" json:"fileUrl,omitempty"`
	MediaLibraryPath string                 `protobuf:"bytes,2,opt,name=mediaLibraryPath,proto3" json:"mediaLibraryPath,omitempty"`
	SaveFileName     string                 `protobuf:"bytes,3,opt,name=saveFileName,proto3" json:"saveFileName,omitempty"`
	Action           string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	AddBase64        string                 `protobuf:"bytes,5,opt,name=addBase64,proto3" json:"addBase64,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MediaLibraryUploadFromUrlRequest) Reset() {
	*x = MediaLibraryUploadFromUrlRequest{}
	mi := &file_core_core_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaLibraryUploadFromUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaLibraryUploadFromUrlRequest) ProtoMessage() {}

func (x *MediaLibraryUploadFromUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaLibraryUploadFromUrlRequest.ProtoReflect.Descriptor instead.
func (*MediaLibraryUploadFromUrlRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{24}
}

func (x *MediaLibraryUploadFromUrlRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *MediaLibraryUploadFromUrlRequest) GetMediaLibraryPath() string {
	if x != nil {
		return x.MediaLibraryPath
	}
	return ""
}

func (x *MediaLibraryUploadFromUrlRequest) GetSaveFileName() string {
	if x != nil {
		return x.SaveFileName
	}
	return ""
}

func (x *MediaLibraryUploadFromUrlRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *MediaLibraryUploadFromUrlRequest) GetAddBase64() string {
	if x != nil {
		return x.AddBase64
	}
	return ""
}

type MediaLibraryUploadFromBase64Request struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Base64Str        string                 `protobuf:"bytes,1,opt,name=base64Str,proto3" json:"base64Str,omitempty"`
	MediaLibraryPath string                 `protobuf:"bytes,2,opt,name=mediaLibraryPath,proto3" json:"mediaLibraryPath,omitempty"`
	SaveFileName     string                 `protobuf:"bytes,3,opt,name=saveFileName,proto3" json:"saveFileName,omitempty"`
	Action           string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MediaLibraryUploadFromBase64Request) Reset() {
	*x = MediaLibraryUploadFromBase64Request{}
	mi := &file_core_core_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaLibraryUploadFromBase64Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaLibraryUploadFromBase64Request) ProtoMessage() {}

func (x *MediaLibraryUploadFromBase64Request) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaLibraryUploadFromBase64Request.ProtoReflect.Descriptor instead.
func (*MediaLibraryUploadFromBase64Request) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{25}
}

func (x *MediaLibraryUploadFromBase64Request) GetBase64Str() string {
	if x != nil {
		return x.Base64Str
	}
	return ""
}

func (x *MediaLibraryUploadFromBase64Request) GetMediaLibraryPath() string {
	if x != nil {
		return x.MediaLibraryPath
	}
	return ""
}

func (x *MediaLibraryUploadFromBase64Request) GetSaveFileName() string {
	if x != nil {
		return x.SaveFileName
	}
	return ""
}

func (x *MediaLibraryUploadFromBase64Request) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type MediaLibraryDirSettingQueryByPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaLibraryDirSettingQueryByPathRequest) Reset() {
	*x = MediaLibraryDirSettingQueryByPathRequest{}
	mi := &file_core_core_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaLibraryDirSettingQueryByPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaLibraryDirSettingQueryByPathRequest) ProtoMessage() {}

func (x *MediaLibraryDirSettingQueryByPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaLibraryDirSettingQueryByPathRequest.ProtoReflect.Descriptor instead.
func (*MediaLibraryDirSettingQueryByPathRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{26}
}

func (x *MediaLibraryDirSettingQueryByPathRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type MediaLibraryDirMkDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Catalog       string                 `protobuf:"bytes,1,opt,name=catalog,proto3" json:"catalog,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaLibraryDirMkDirRequest) Reset() {
	*x = MediaLibraryDirMkDirRequest{}
	mi := &file_core_core_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaLibraryDirMkDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaLibraryDirMkDirRequest) ProtoMessage() {}

func (x *MediaLibraryDirMkDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaLibraryDirMkDirRequest.ProtoReflect.Descriptor instead.
func (*MediaLibraryDirMkDirRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{27}
}

func (x *MediaLibraryDirMkDirRequest) GetCatalog() string {
	if x != nil {
		return x.Catalog
	}
	return ""
}

func (x *MediaLibraryDirMkDirRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MediaLibraryDeleteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Files          []string               `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	CompleteDelete bool                   `protobuf:"varint,2,opt,name=completeDelete,proto3" json:"completeDelete,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MediaLibraryDeleteRequest) Reset() {
	*x = MediaLibraryDeleteRequest{}
	mi := &file_core_core_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaLibraryDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaLibraryDeleteRequest) ProtoMessage() {}

func (x *MediaLibraryDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaLibraryDeleteRequest.ProtoReflect.Descriptor instead.
func (*MediaLibraryDeleteRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{28}
}

func (x *MediaLibraryDeleteRequest) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *MediaLibraryDeleteRequest) GetCompleteDelete() bool {
	if x != nil {
		return x.CompleteDelete
	}
	return false
}

var File_core_core_proto protoreflect.FileDescriptor

const file_core_core_proto_rawDesc = "" +
	"\n" +
	"\x0fcore/core.proto\x12\x04core\x1a\rapi/api.proto\"\x1e\n" +
	"\x1cAuthorizationRevisionRequest\"T\n" +
	"\x1dAuthorizationRevisionResponse\x123\n" +
	"\x15authorization_version\x18\x01 \x01(\x03R\x14authorizationVersion\"I\n" +
	"\x1eAuthorizationPermissionRequest\x12'\n" +
	"\x0fpermission_code\x18\x01 \x01(\tR\x0epermissionCode\"\x86\x01\n" +
	"\x15AuthorizationDecision\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x123\n" +
	"\x15authorization_version\x18\x02 \x01(\x03R\x14authorizationVersion\x12\x1e\n" +
	"\n" +
	"privileged\x18\x03 \x01(\bR\n" +
	"privileged\"\xa3\x01\n" +
	"\x15AuthorizationResource\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12,\n" +
	"\x12parent_resource_id\x18\x02 \x01(\tR\x10parentResourceId\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\"W\n" +
	"\x1aBatchResourceAccessRequest\x129\n" +
	"\tresources\x18\x01 \x03(\v2\x1b.core.AuthorizationResourceR\tresources\"k\n" +
	"\x16ResourceAccessDecision\x127\n" +
	"\bresource\x18\x01 \x01(\v2\x1b.core.AuthorizationResourceR\bresource\x12\x18\n" +
	"\aallowed\x18\x02 \x01(\bR\aallowed\"\x8e\x01\n" +
	"\x1bBatchResourceAccessResponse\x12:\n" +
	"\tdecisions\x18\x01 \x03(\v2\x1c.core.ResourceAccessDecisionR\tdecisions\x123\n" +
	"\x15authorization_version\x18\x02 \x01(\x03R\x14authorizationVersion\"\x8b\x01\n" +
	"\x1eListAccessibleResourcesRequest\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12,\n" +
	"\x12parent_resource_id\x18\x02 \x01(\tR\x10parentResourceId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"\xd8\x01\n" +
	"\x1fListAccessibleResourcesResponse\x12!\n" +
	"\fresource_ids\x18\x01 \x03(\tR\vresourceIds\x12\"\n" +
	"\funrestricted\x18\x02 \x01(\bR\funrestricted\x123\n" +
	"\x15authorization_version\x18\x03 \x01(\x03R\x14authorizationVersion\x129\n" +
	"\tresources\x18\x04 \x03(\v2\x1b.core.AuthorizationResourceR\tresources\"@\n" +
	"\x10GetDeviceRequest\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\"j\n" +
	"\x14GetDataDeviceRequest\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x14\n" +
	"\x05table\x18\x03 \x01(\tR\x05table\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\"$\n" +
	"\x0eGetRequestName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"/\n" +
	"\x13VerifyAPIKeyRequest\x12\x18\n" +
	"\afullKey\x18\x01 \x01(\tR\afullKey\".\n" +
	"\x14VerifyAPIKeyResponse\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\">\n" +
	"\x10QueryDataRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x14\n" +
	"\x05query\x18\x02 \x01(\fR\x05query\">\n" +
	"\x16GetOrDeleteDataRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"q\n" +
	"\x11UpdateDataRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\"\n" +
	"\fcloseRequire\x18\x04 \x01(\bR\fcloseRequire\"|\n" +
	"\x16MultiUpdateDataRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x14\n" +
	"\x05query\x18\x02 \x01(\fR\x05query\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\"\n" +
	"\fcloseRequire\x18\x04 \x01(\bR\fcloseRequire\"a\n" +
	"\x11CreateDataRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\"\n" +
	"\fcloseRequire\x18\x03 \x01(\bR\fcloseRequire\"(\n" +
	"\x10LoginUserRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"'\n" +
	"\x11UploadFileRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"*\n" +
	"\x14DownloadFileResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x80\x01\n" +
	"\x18MediaLibraryQueryRequest\x12\x18\n" +
	"\acatalog\x18\x01 \x01(\tR\acatalog\x12\x1c\n" +
	"\taddBase64\x18\x02 \x01(\bR\taddBase64\x12\x16\n" +
	"\x06isFile\x18\x03 \x01(\bR\x06isFile\x12\x14\n" +
	"\x05query\x18\x04 \x01(\fR\x05query\"\xc2\x01\n" +
	" MediaLibraryUploadFromUrlRequest\x12\x18\n" +
	"\afileUrl\x18\x01 \x01(\tR\afileUrl\x12*\n" +
	"\x10mediaLibraryPath\x18\x02 \x01(\tR\x10mediaLibraryPath\x12\"\n" +
	"\fsaveFileName\x18\x03 \x01(\tR\fsaveFileName\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1c\n" +
	"\taddBase64\x18\x05 \x01(\tR\taddBase64\"\xab\x01\n" +
	"#MediaLibraryUploadFromBase64Request\x12\x1c\n" +
	"\tbase64Str\x18\x01 \x01(\tR\tbase64Str\x12*\n" +
	"\x10mediaLibraryPath\x18\x02 \x01(\tR\x10mediaLibraryPath\x12\"\n" +
	"\fsaveFileName\x18\x03 \x01(\tR\fsaveFileName\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\">\n" +
	"(MediaLibraryDirSettingQueryByPathRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"K\n" +
	"\x1bMediaLibraryDirMkDirRequest\x12\x18\n" +
	"\acatalog\x18\x01 \x01(\tR\acatalog\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"Y\n" +
	"\x19MediaLibraryDeleteRequest\x12\x14\n" +
	"\x05files\x18\x01 \x03(\tR\x05files\x12&\n" +
	"\x0ecompleteDelete\x18\x02 \x01(\bR\x0ecompleteDelete2\xaa\x02\n" +
	"\x0eLicenseService\x124\n" +
	"\x0eGetFileLicense\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x120\n" +
	"\n" +
	"UseLicense\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x125\n" +
	"\x0fFindMachineCode\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12<\n" +
	"\x10GetDriverLicense\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12;\n" +
	"\rUploadLicense\x12\x17.core.UploadFileRequest\x1a\r.api.Response\"\x00(\x012\x9a\x01\n" +
	"\n" +
	"AppService\x12.\n" +
	"\bGetToken\x12\x11.api.TokenRequest\x1a\r.api.Response\"\x00\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x002\x8f\x02\n" +
	"\n" +
	"LogService\x12-\n" +
	"\x06Create\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x128\n" +
	"\x12QueryApiPermission\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12:\n" +
	"\x13CreateApiPermission\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x002\x81\x05\n" +
	"\vUserService\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\x06Delete\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Update\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12.\n" +
	"\aReplace\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Create\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x12=\n" +
	"\x12GetCurrentUserInfo\x12\x16.core.LoginUserRequest\x1a\r.api.Response\"\x00\x12;\n" +
	"\x14UserPermissionUpdate\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x121\n" +
	"\vQueryBackup\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x126\n" +
	"\x10DeleteManyBackup\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x127\n" +
	"\x10CreateManyBackup\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\vCallAIModel\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x002\xc8\x02\n" +
	"\rAPIKeyService\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Create\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\x06Delete\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x123\n" +
	"\n" +
	"GetByKeyID\x12\x14.core.GetRequestName\x1a\r.api.Response\"\x00\x12A\n" +
	"\x06Verify\x12\x19.core.VerifyAPIKeyRequest\x1a\x1a.core.VerifyAPIKeyResponse\"\x002\xa8\x05\n" +
	"\x12TableSchemaService\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12F\n" +
	"\x1bQueryDeviceByDriverAndGroup\x12\x16.core.GetDeviceRequest\x1a\r.api.Response\"\x00\x12K\n" +
	" QueryTableDeviceByDriverAndGroup\x12\x16.core.GetDeviceRequest\x1a\r.api.Response\"\x00\x129\n" +
	"\n" +
	"FindDevice\x12\x1a.core.GetDataDeviceRequest\x1a\r.api.Response\"\x00\x123\n" +
	"\rQueryEmulator\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\x06Delete\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Update\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12.\n" +
	"\aReplace\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Create\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x120\n" +
	"\n" +
	"StatsQuery\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12;\n" +
	"\x0fFindCommandByID\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x002\xc3\n" +
	"\n" +
	"\x10TableDataService\x120\n" +
	"\x05Query\x12\x16.core.QueryDataRequest\x1a\r.api.Response\"\x00\x129\n" +
	"\x0eQueryByTableId\x12\x16.core.QueryDataRequest\x1a\r.api.Response\"\x00\x124\n" +
	"\x03Get\x12\x1c.core.GetOrDeleteDataRequest\x1a\r.api.Response\"\x00\x127\n" +
	"\x06Delete\x12\x1c.core.GetOrDeleteDataRequest\x1a\r.api.Response\"\x00\x125\n" +
	"\n" +
	"DeleteMany\x12\x16.core.QueryDataRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\x06Update\x12\x17.core.UpdateDataRequest\x1a\r.api.Response\"\x00\x123\n" +
	"\aReplace\x12\x17.core.UpdateDataRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\x06Create\x12\x17.core.CreateDataRequest\x1a\r.api.Response\"\x00\x126\n" +
	"\n" +
	"CreateMany\x12\x17.core.CreateDataRequest\x1a\r.api.Response\"\x00\x12A\n" +
	"\x1aFindTableDataDeptByDeptIDs\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x12;\n" +
	"\n" +
	"UpdateMany\x12\x1c.core.MultiUpdateDataRequest\x1a\r.api.Response\"\x00\x129\n" +
	"\x13GetWarningFilterIDs\x12\x11.api.EmptyRequest\x1a\r.api.Response\"\x00\x12<\n" +
	"\vFindTagByID\x12\x1c.core.GetOrDeleteDataRequest\x1a\r.api.Response\"\x00\x12@\n" +
	"\x0fFindCommandByID\x12\x1c.core.GetOrDeleteDataRequest\x1a\r.api.Response\"\x00\x124\n" +
	"\tQueryByDB\x12\x16.core.QueryDataRequest\x1a\r.api.Response\"\x00\x128\n" +
	"\aGetByDB\x12\x1c.core.GetOrDeleteDataRequest\x1a\r.api.Response\"\x00\x12;\n" +
	"\n" +
	"DeleteByDB\x12\x1c.core.GetOrDeleteDataRequest\x1a\r.api.Response\"\x00\x129\n" +
	"\x0eDeleteManyByDB\x12\x16.core.QueryDataRequest\x1a\r.api.Response\"\x00\x126\n" +
	"\n" +
	"UpdateByDB\x12\x17.core.UpdateDataRequest\x1a\r.api.Response\"\x00\x127\n" +
	"\vReplaceByDB\x12\x17.core.UpdateDataRequest\x1a\r.api.Response\"\x00\x126\n" +
	"\n" +
	"CreateByDB\x12\x17.core.CreateDataRequest\x1a\r.api.Response\"\x00\x12:\n" +
	"\x0eCreateManyByDB\x12\x17.core.CreateDataRequest\x1a\r.api.Response\"\x00\x12?\n" +
	"\x0eUpdateManyByDB\x12\x1c.core.MultiUpdateDataRequest\x1a\r.api.Response\"\x002\xb4\x02\n" +
	"\x12TableRecordService\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\x06Delete\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Update\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12.\n" +
	"\aReplace\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Create\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x002l\n" +
	"\x0eMessageService\x12-\n" +
	"\x06Create\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x002n\n" +
	"\x10DashboardService\x12-\n" +
	"\x06Create\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x002\xa7\x01\n" +
	"\x10DataQueryService\x121\n" +
	"\n" +
	"PostLatest\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x12.\n" +
	"\bGetQuery\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x120\n" +
	"\tPostQuery\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x002\xa1\x01\n" +
	"\vRoleService\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x124\n" +
	"\x0eAdminRoleCheck\x12\x11.api.EmptyRequest\x1a\r.api.Response\"\x002n\n" +
	"\x0eCatalogService\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x002k\n" +
	"\vDeptService\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x002=\n" +
	"\x0eSettingService\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x002\xb7\x02\n" +
	"\x15SystemVariableService\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\x06Delete\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Update\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12.\n" +
	"\aReplace\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Create\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x002\xa7\x03\n" +
	"\rBackupService\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\x06Delete\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Update\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12,\n" +
	"\x06Import\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12,\n" +
	"\x06Export\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x124\n" +
	"\x06Upload\x12\x17.core.UploadFileRequest\x1a\r.api.Response\"\x00(\x01\x12C\n" +
	"\bDownload\x12\x17.api.GetOrDeleteRequest\x1a\x1a.core.DownloadFileResponse\"\x000\x012\xb4\x02\n" +
	"\x12TaskManagerService\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\x06Delete\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Update\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12.\n" +
	"\aReplace\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Create\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x002\xe7\x02\n" +
	"\x13MediaLibraryService\x128\n" +
	"\x05Query\x12\x1e.core.MediaLibraryQueryRequest\x1a\r.api.Response\"\x00\x12H\n" +
	"\rUploadFromUrl\x12&.core.MediaLibraryUploadFromUrlRequest\x1a\r.api.Response\"\x00\x12N\n" +
	"\x10UploadFromBase64\x12).core.MediaLibraryUploadFromBase64Request\x1a\r.api.Response\"\x00\x12;\n" +
	"\x05Mkdir\x12!.core.MediaLibraryDirMkDirRequest\x1a\r.api.Response\"\x00\x12?\n" +
	"\vDeleteFiles\x12\x1f.core.MediaLibraryDeleteRequest\x1a\r.api.Response\"\x002\x8d\x03\n" +
	"\x1dMediaLibraryDirSettingService\x12-\n" +
	"\x06Create\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\x06Delete\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Update\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12.\n" +
	"\aReplace\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12L\n" +
	"\tGetByPath\x12..core.MediaLibraryDirSettingQueryByPathRequest\x1a\r.api.Response\"\x00\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x002\xa2\x03\n" +
	"\x14AuthorizationService\x12V\n" +
	"\x0fCheckPermission\x12$.core.AuthorizationPermissionRequest\x1a\x1b.core.AuthorizationDecision\"\x00\x12a\n" +
	"\x18BatchCheckResourceAccess\x12 .core.BatchResourceAccessRequest\x1a!.core.BatchResourceAccessResponse\"\x00\x12h\n" +
	"\x17ListAccessibleResources\x12$.core.ListAccessibleResourcesRequest\x1a%.core.ListAccessibleResourcesResponse\"\x00\x12e\n" +
	"\x18GetAuthorizationRevision\x12\".core.AuthorizationRevisionRequest\x1a#.core.AuthorizationRevisionResponse\"\x00B;\n" +
	"$cn.gtsiot.sdk.client.dubbo.grpc.coreP\x01Z\v./core;core\x88\x01\x01\xa0\x01\x01b\x06proto3"

var (
	file_core_core_proto_rawDescOnce sync.Once
	file_core_core_proto_rawDescData []byte
)

func file_core_core_proto_rawDescGZIP() []byte {
	file_core_core_proto_rawDescOnce.Do(func() {
		file_core_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_core_proto_rawDesc), len(file_core_core_proto_rawDesc)))
	})
	return file_core_core_proto_rawDescData
}

var file_core_core_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_core_core_proto_goTypes = []any{
	(*AuthorizationRevisionRequest)(nil),             // 0: core.AuthorizationRevisionRequest
	(*AuthorizationRevisionResponse)(nil),            // 1: core.AuthorizationRevisionResponse
	(*AuthorizationPermissionRequest)(nil),           // 2: core.AuthorizationPermissionRequest
	(*AuthorizationDecision)(nil),                    // 3: core.AuthorizationDecision
	(*AuthorizationResource)(nil),                    // 4: core.AuthorizationResource
	(*BatchResourceAccessRequest)(nil),               // 5: core.BatchResourceAccessRequest
	(*ResourceAccessDecision)(nil),                   // 6: core.ResourceAccessDecision
	(*BatchResourceAccessResponse)(nil),              // 7: core.BatchResourceAccessResponse
	(*ListAccessibleResourcesRequest)(nil),           // 8: core.ListAccessibleResourcesRequest
	(*ListAccessibleResourcesResponse)(nil),          // 9: core.ListAccessibleResourcesResponse
	(*GetDeviceRequest)(nil),                         // 10: core.GetDeviceRequest
	(*GetDataDeviceRequest)(nil),                     // 11: core.GetDataDeviceRequest
	(*GetRequestName)(nil),                           // 12: core.GetRequestName
	(*VerifyAPIKeyRequest)(nil),                      // 13: core.VerifyAPIKeyRequest
	(*VerifyAPIKeyResponse)(nil),                     // 14: core.VerifyAPIKeyResponse
	(*QueryDataRequest)(nil),                         // 15: core.QueryDataRequest
	(*GetOrDeleteDataRequest)(nil),                   // 16: core.GetOrDeleteDataRequest
	(*UpdateDataRequest)(nil),                        // 17: core.UpdateDataRequest
	(*MultiUpdateDataRequest)(nil),                   // 18: core.MultiUpdateDataRequest
	(*CreateDataRequest)(nil),                        // 19: core.CreateDataRequest
	(*LoginUserRequest)(nil),                         // 20: core.LoginUserRequest
	(*UploadFileRequest)(nil),                        // 21: core.UploadFileRequest
	(*DownloadFileResponse)(nil),                     // 22: core.DownloadFileResponse
	(*MediaLibraryQueryRequest)(nil),                 // 23: core.MediaLibraryQueryRequest
	(*MediaLibraryUploadFromUrlRequest)(nil),         // 24: core.MediaLibraryUploadFromUrlRequest
	(*MediaLibraryUploadFromBase64Request)(nil),      // 25: core.MediaLibraryUploadFromBase64Request
	(*MediaLibraryDirSettingQueryByPathRequest)(nil), // 26: core.MediaLibraryDirSettingQueryByPathRequest
	(*MediaLibraryDirMkDirRequest)(nil),              // 27: core.MediaLibraryDirMkDirRequest
	(*MediaLibraryDeleteRequest)(nil),                // 28: core.MediaLibraryDeleteRequest
	(*api.QueryRequest)(nil),                         // 29: api.QueryRequest
	(*api.GetOrDeleteRequest)(nil),                   // 30: api.GetOrDeleteRequest
	(*api.TokenRequest)(nil),                         // 31: api.TokenRequest
	(*api.CreateRequest)(nil),                        // 32: api.CreateRequest
	(*api.UpdateRequest)(nil),                        // 33: api.UpdateRequest
	(*api.EmptyRequest)(nil),                         // 34: api.EmptyRequest
	(*api.Response)(nil),                             // 35: api.Response
}
var file_core_core_proto_depIdxs = []int32{
	4,   // 0: core.BatchResourceAccessRequest.resources:type_name -> core.AuthorizationResource
	4,   // 1: core.ResourceAccessDecision.resource:type_name -> core.AuthorizationResource
	6,   // 2: core.BatchResourceAccessResponse.decisions:type_name -> core.ResourceAccessDecision
	4,   // 3: core.ListAccessibleResourcesResponse.resources:type_name -> core.AuthorizationResource
	29,  // 4: core.LicenseService.GetFileLicense:input_type -> api.QueryRequest
	29,  // 5: core.LicenseService.UseLicense:input_type -> api.QueryRequest
	29,  // 6: core.LicenseService.FindMachineCode:input_type -> api.QueryRequest
	30,  // 7: core.LicenseService.GetDriverLicense:input_type -> api.GetOrDeleteRequest
	21,  // 8: core.LicenseService.UploadLicense:input_type -> core.UploadFileRequest
	31,  // 9: core.AppService.GetToken:input_type -> api.TokenRequest
	29,  // 10: core.AppService.Query:input_type -> api.QueryRequest
	30,  // 11: core.AppService.Get:input_type -> api.GetOrDeleteRequest
	32,  // 12: core.LogService.Create:input_type -> api.CreateRequest
	30,  // 13: core.LogService.Get:input_type -> api.GetOrDeleteRequest
	29,  // 14: core.LogService.Query:input_type -> api.QueryRequest
	29,  // 15: core.LogService.QueryApiPermission:input_type -> api.QueryRequest
	32,  // 16: core.LogService.CreateApiPermission:input_type -> api.CreateRequest
	29,  // 17: core.UserService.Query:input_type -> api.QueryRequest
	30,  // 18: core.UserService.Get:input_type -> api.GetOrDeleteRequest
	30,  // 19: core.UserService.Delete:input_type -> api.GetOrDeleteRequest
	33,  // 20: core.UserService.Update:input_type -> api.UpdateRequest
	33,  // 21: core.UserService.Replace:input_type -> api.UpdateRequest
	32,  // 22: core.UserService.Create:input_type -> api.CreateRequest
	20,  // 23: core.UserService.GetCurrentUserInfo:input_type -> core.LoginUserRequest
	32,  // 24: core.UserService.UserPermissionUpdate:input_type -> api.CreateRequest
	29,  // 25: core.UserService.QueryBackup:input_type -> api.QueryRequest
	29,  // 26: core.UserService.DeleteManyBackup:input_type -> api.QueryRequest
	32,  // 27: core.UserService.CreateManyBackup:input_type -> api.CreateRequest
	32,  // 28: core.UserService.CallAIModel:input_type -> api.CreateRequest
	29,  // 29: core.APIKeyService.Query:input_type -> api.QueryRequest
	30,  // 30: core.APIKeyService.Get:input_type -> api.GetOrDeleteRequest
	32,  // 31: core.APIKeyService.Create:input_type -> api.CreateRequest
	30,  // 32: core.APIKeyService.Delete:input_type -> api.GetOrDeleteRequest
	12,  // 33: core.APIKeyService.GetByKeyID:input_type -> core.GetRequestName
	13,  // 34: core.APIKeyService.Verify:input_type -> core.VerifyAPIKeyRequest
	29,  // 35: core.TableSchemaService.Query:input_type -> api.QueryRequest
	10,  // 36: core.TableSchemaService.QueryDeviceByDriverAndGroup:input_type -> core.GetDeviceRequest
	10,  // 37: core.TableSchemaService.QueryTableDeviceByDriverAndGroup:input_type -> core.GetDeviceRequest
	11,  // 38: core.TableSchemaService.FindDevice:input_type -> core.GetDataDeviceRequest
	29,  // 39: core.TableSchemaService.QueryEmulator:input_type -> api.QueryRequest
	30,  // 40: core.TableSchemaService.Get:input_type -> api.GetOrDeleteRequest
	30,  // 41: core.TableSchemaService.Delete:input_type -> api.GetOrDeleteRequest
	33,  // 42: core.TableSchemaService.Update:input_type -> api.UpdateRequest
	33,  // 43: core.TableSchemaService.Replace:input_type -> api.UpdateRequest
	32,  // 44: core.TableSchemaService.Create:input_type -> api.CreateRequest
	29,  // 45: core.TableSchemaService.StatsQuery:input_type -> api.QueryRequest
	30,  // 46: core.TableSchemaService.FindCommandByID:input_type -> api.GetOrDeleteRequest
	15,  // 47: core.TableDataService.Query:input_type -> core.QueryDataRequest
	15,  // 48: core.TableDataService.QueryByTableId:input_type -> core.QueryDataRequest
	16,  // 49: core.TableDataService.Get:input_type -> core.GetOrDeleteDataRequest
	16,  // 50: core.TableDataService.Delete:input_type -> core.GetOrDeleteDataRequest
	15,  // 51: core.TableDataService.DeleteMany:input_type -> core.QueryDataRequest
	17,  // 52: core.TableDataService.Update:input_type -> core.UpdateDataRequest
	17,  // 53: core.TableDataService.Replace:input_type -> core.UpdateDataRequest
	19,  // 54: core.TableDataService.Create:input_type -> core.CreateDataRequest
	19,  // 55: core.TableDataService.CreateMany:input_type -> core.CreateDataRequest
	32,  // 56: core.TableDataService.FindTableDataDeptByDeptIDs:input_type -> api.CreateRequest
	18,  // 57: core.TableDataService.UpdateMany:input_type -> core.MultiUpdateDataRequest
	34,  // 58: core.TableDataService.GetWarningFilterIDs:input_type -> api.EmptyRequest
	16,  // 59: core.TableDataService.FindTagByID:input_type -> core.GetOrDeleteDataRequest
	16,  // 60: core.TableDataService.FindCommandByID:input_type -> core.GetOrDeleteDataRequest
	15,  // 61: core.TableDataService.QueryByDB:input_type -> core.QueryDataRequest
	16,  // 62: core.TableDataService.GetByDB:input_type -> core.GetOrDeleteDataRequest
	16,  // 63: core.TableDataService.DeleteByDB:input_type -> core.GetOrDeleteDataRequest
	15,  // 64: core.TableDataService.DeleteManyByDB:input_type -> core.QueryDataRequest
	17,  // 65: core.TableDataService.UpdateByDB:input_type -> core.UpdateDataRequest
	17,  // 66: core.TableDataService.ReplaceByDB:input_type -> core.UpdateDataRequest
	19,  // 67: core.TableDataService.CreateByDB:input_type -> core.CreateDataRequest
	19,  // 68: core.TableDataService.CreateManyByDB:input_type -> core.CreateDataRequest
	18,  // 69: core.TableDataService.UpdateManyByDB:input_type -> core.MultiUpdateDataRequest
	29,  // 70: core.TableRecordService.Query:input_type -> api.QueryRequest
	30,  // 71: core.TableRecordService.Get:input_type -> api.GetOrDeleteRequest
	30,  // 72: core.TableRecordService.Delete:input_type -> api.GetOrDeleteRequest
	33,  // 73: core.TableRecordService.Update:input_type -> api.UpdateRequest
	33,  // 74: core.TableRecordService.Replace:input_type -> api.UpdateRequest
	32,  // 75: core.TableRecordService.Create:input_type -> api.CreateRequest
	32,  // 76: core.MessageService.Create:input_type -> api.CreateRequest
	29,  // 77: core.MessageService.Query:input_type -> api.QueryRequest
	32,  // 78: core.DashboardService.Create:input_type -> api.CreateRequest
	29,  // 79: core.DashboardService.Query:input_type -> api.QueryRequest
	32,  // 80: core.DataQueryService.PostLatest:input_type -> api.CreateRequest
	29,  // 81: core.DataQueryService.GetQuery:input_type -> api.QueryRequest
	32,  // 82: core.DataQueryService.PostQuery:input_type -> api.CreateRequest
	29,  // 83: core.RoleService.Query:input_type -> api.QueryRequest
	30,  // 84: core.RoleService.Get:input_type -> api.GetOrDeleteRequest
	34,  // 85: core.RoleService.AdminRoleCheck:input_type -> api.EmptyRequest
	29,  // 86: core.CatalogService.Query:input_type -> api.QueryRequest
	30,  // 87: core.CatalogService.Get:input_type -> api.GetOrDeleteRequest
	29,  // 88: core.DeptService.Query:input_type -> api.QueryRequest
	30,  // 89: core.DeptService.Get:input_type -> api.GetOrDeleteRequest
	29,  // 90: core.SettingService.Query:input_type -> api.QueryRequest
	29,  // 91: core.SystemVariableService.Query:input_type -> api.QueryRequest
	30,  // 92: core.SystemVariableService.Get:input_type -> api.GetOrDeleteRequest
	30,  // 93: core.SystemVariableService.Delete:input_type -> api.GetOrDeleteRequest
	33,  // 94: core.SystemVariableService.Update:input_type -> api.UpdateRequest
	33,  // 95: core.SystemVariableService.Replace:input_type -> api.UpdateRequest
	32,  // 96: core.SystemVariableService.Create:input_type -> api.CreateRequest
	29,  // 97: core.BackupService.Query:input_type -> api.QueryRequest
	30,  // 98: core.BackupService.Get:input_type -> api.GetOrDeleteRequest
	30,  // 99: core.BackupService.Delete:input_type -> api.GetOrDeleteRequest
	33,  // 100: core.BackupService.Update:input_type -> api.UpdateRequest
	29,  // 101: core.BackupService.Import:input_type -> api.QueryRequest
	29,  // 102: core.BackupService.Export:input_type -> api.QueryRequest
	21,  // 103: core.BackupService.Upload:input_type -> core.UploadFileRequest
	30,  // 104: core.BackupService.Download:input_type -> api.GetOrDeleteRequest
	29,  // 105: core.TaskManagerService.Query:input_type -> api.QueryRequest
	30,  // 106: core.TaskManagerService.Get:input_type -> api.GetOrDeleteRequest
	30,  // 107: core.TaskManagerService.Delete:input_type -> api.GetOrDeleteRequest
	33,  // 108: core.TaskManagerService.Update:input_type -> api.UpdateRequest
	33,  // 109: core.TaskManagerService.Replace:input_type -> api.UpdateRequest
	32,  // 110: core.TaskManagerService.Create:input_type -> api.CreateRequest
	23,  // 111: core.MediaLibraryService.Query:input_type -> core.MediaLibraryQueryRequest
	24,  // 112: core.MediaLibraryService.UploadFromUrl:input_type -> core.MediaLibraryUploadFromUrlRequest
	25,  // 113: core.MediaLibraryService.UploadFromBase64:input_type -> core.MediaLibraryUploadFromBase64Request
	27,  // 114: core.MediaLibraryService.Mkdir:input_type -> core.MediaLibraryDirMkDirRequest
	28,  // 115: core.MediaLibraryService.DeleteFiles:input_type -> core.MediaLibraryDeleteRequest
	32,  // 116: core.MediaLibraryDirSettingService.Create:input_type -> api.CreateRequest
	30,  // 117: core.MediaLibraryDirSettingService.Delete:input_type -> api.GetOrDeleteRequest
	33,  // 118: core.MediaLibraryDirSettingService.Update:input_type -> api.UpdateRequest
	33,  // 119: core.MediaLibraryDirSettingService.Replace:input_type -> api.UpdateRequest
	30,  // 120: core.MediaLibraryDirSettingService.Get:input_type -> api.GetOrDeleteRequest
	26,  // 121: core.MediaLibraryDirSettingService.GetByPath:input_type -> core.MediaLibraryDirSettingQueryByPathRequest
	29,  // 122: core.MediaLibraryDirSettingService.Query:input_type -> api.QueryRequest
	2,   // 123: core.AuthorizationService.CheckPermission:input_type -> core.AuthorizationPermissionRequest
	5,   // 124: core.AuthorizationService.BatchCheckResourceAccess:input_type -> core.BatchResourceAccessRequest
	8,   // 125: core.AuthorizationService.ListAccessibleResources:input_type -> core.ListAccessibleResourcesRequest
	0,   // 126: core.AuthorizationService.GetAuthorizationRevision:input_type -> core.AuthorizationRevisionRequest
	35,  // 127: core.LicenseService.GetFileLicense:output_type -> api.Response
	35,  // 128: core.LicenseService.UseLicense:output_type -> api.Response
	35,  // 129: core.LicenseService.FindMachineCode:output_type -> api.Response
	35,  // 130: core.LicenseService.GetDriverLicense:output_type -> api.Response
	35,  // 131: core.LicenseService.UploadLicense:output_type -> api.Response
	35,  // 132: core.AppService.GetToken:output_type -> api.Response
	35,  // 133: core.AppService.Query:output_type -> api.Response
	35,  // 134: core.AppService.Get:output_type -> api.Response
	35,  // 135: core.LogService.Create:output_type -> api.Response
	35,  // 136: core.LogService.Get:output_type -> api.Response
	35,  // 137: core.LogService.Query:output_type -> api.Response
	35,  // 138: core.LogService.QueryApiPermission:output_type -> api.Response
	35,  // 139: core.LogService.CreateApiPermission:output_type -> api.Response
	35,  // 140: core.UserService.Query:output_type -> api.Response
	35,  // 141: core.UserService.Get:output_type -> api.Response
	35,  // 142: core.UserService.Delete:output_type -> api.Response
	35,  // 143: core.UserService.Update:output_type -> api.Response
	35,  // 144: core.UserService.Replace:output_type -> api.Response
	35,  // 145: core.UserService.Create:output_type -> api.Response
	35,  // 146: core.UserService.GetCurrentUserInfo:output_type -> api.Response
	35,  // 147: core.UserService.UserPermissionUpdate:output_type -> api.Response
	35,  // 148: core.UserService.QueryBackup:output_type -> api.Response
	35,  // 149: core.UserService.DeleteManyBackup:output_type -> api.Response
	35,  // 150: core.UserService.CreateManyBackup:output_type -> api.Response
	35,  // 151: core.UserService.CallAIModel:output_type -> api.Response
	35,  // 152: core.APIKeyService.Query:output_type -> api.Response
	35,  // 153: core.APIKeyService.Get:output_type -> api.Response
	35,  // 154: core.APIKeyService.Create:output_type -> api.Response
	35,  // 155: core.APIKeyService.Delete:output_type -> api.Response
	35,  // 156: core.APIKeyService.GetByKeyID:output_type -> api.Response
	14,  // 157: core.APIKeyService.Verify:output_type -> core.VerifyAPIKeyResponse
	35,  // 158: core.TableSchemaService.Query:output_type -> api.Response
	35,  // 159: core.TableSchemaService.QueryDeviceByDriverAndGroup:output_type -> api.Response
	35,  // 160: core.TableSchemaService.QueryTableDeviceByDriverAndGroup:output_type -> api.Response
	35,  // 161: core.TableSchemaService.FindDevice:output_type -> api.Response
	35,  // 162: core.TableSchemaService.QueryEmulator:output_type -> api.Response
	35,  // 163: core.TableSchemaService.Get:output_type -> api.Response
	35,  // 164: core.TableSchemaService.Delete:output_type -> api.Response
	35,  // 165: core.TableSchemaService.Update:output_type -> api.Response
	35,  // 166: core.TableSchemaService.Replace:output_type -> api.Response
	35,  // 167: core.TableSchemaService.Create:output_type -> api.Response
	35,  // 168: core.TableSchemaService.StatsQuery:output_type -> api.Response
	35,  // 169: core.TableSchemaService.FindCommandByID:output_type -> api.Response
	35,  // 170: core.TableDataService.Query:output_type -> api.Response
	35,  // 171: core.TableDataService.QueryByTableId:output_type -> api.Response
	35,  // 172: core.TableDataService.Get:output_type -> api.Response
	35,  // 173: core.TableDataService.Delete:output_type -> api.Response
	35,  // 174: core.TableDataService.DeleteMany:output_type -> api.Response
	35,  // 175: core.TableDataService.Update:output_type -> api.Response
	35,  // 176: core.TableDataService.Replace:output_type -> api.Response
	35,  // 177: core.TableDataService.Create:output_type -> api.Response
	35,  // 178: core.TableDataService.CreateMany:output_type -> api.Response
	35,  // 179: core.TableDataService.FindTableDataDeptByDeptIDs:output_type -> api.Response
	35,  // 180: core.TableDataService.UpdateMany:output_type -> api.Response
	35,  // 181: core.TableDataService.GetWarningFilterIDs:output_type -> api.Response
	35,  // 182: core.TableDataService.FindTagByID:output_type -> api.Response
	35,  // 183: core.TableDataService.FindCommandByID:output_type -> api.Response
	35,  // 184: core.TableDataService.QueryByDB:output_type -> api.Response
	35,  // 185: core.TableDataService.GetByDB:output_type -> api.Response
	35,  // 186: core.TableDataService.DeleteByDB:output_type -> api.Response
	35,  // 187: core.TableDataService.DeleteManyByDB:output_type -> api.Response
	35,  // 188: core.TableDataService.UpdateByDB:output_type -> api.Response
	35,  // 189: core.TableDataService.ReplaceByDB:output_type -> api.Response
	35,  // 190: core.TableDataService.CreateByDB:output_type -> api.Response
	35,  // 191: core.TableDataService.CreateManyByDB:output_type -> api.Response
	35,  // 192: core.TableDataService.UpdateManyByDB:output_type -> api.Response
	35,  // 193: core.TableRecordService.Query:output_type -> api.Response
	35,  // 194: core.TableRecordService.Get:output_type -> api.Response
	35,  // 195: core.TableRecordService.Delete:output_type -> api.Response
	35,  // 196: core.TableRecordService.Update:output_type -> api.Response
	35,  // 197: core.TableRecordService.Replace:output_type -> api.Response
	35,  // 198: core.TableRecordService.Create:output_type -> api.Response
	35,  // 199: core.MessageService.Create:output_type -> api.Response
	35,  // 200: core.MessageService.Query:output_type -> api.Response
	35,  // 201: core.DashboardService.Create:output_type -> api.Response
	35,  // 202: core.DashboardService.Query:output_type -> api.Response
	35,  // 203: core.DataQueryService.PostLatest:output_type -> api.Response
	35,  // 204: core.DataQueryService.GetQuery:output_type -> api.Response
	35,  // 205: core.DataQueryService.PostQuery:output_type -> api.Response
	35,  // 206: core.RoleService.Query:output_type -> api.Response
	35,  // 207: core.RoleService.Get:output_type -> api.Response
	35,  // 208: core.RoleService.AdminRoleCheck:output_type -> api.Response
	35,  // 209: core.CatalogService.Query:output_type -> api.Response
	35,  // 210: core.CatalogService.Get:output_type -> api.Response
	35,  // 211: core.DeptService.Query:output_type -> api.Response
	35,  // 212: core.DeptService.Get:output_type -> api.Response
	35,  // 213: core.SettingService.Query:output_type -> api.Response
	35,  // 214: core.SystemVariableService.Query:output_type -> api.Response
	35,  // 215: core.SystemVariableService.Get:output_type -> api.Response
	35,  // 216: core.SystemVariableService.Delete:output_type -> api.Response
	35,  // 217: core.SystemVariableService.Update:output_type -> api.Response
	35,  // 218: core.SystemVariableService.Replace:output_type -> api.Response
	35,  // 219: core.SystemVariableService.Create:output_type -> api.Response
	35,  // 220: core.BackupService.Query:output_type -> api.Response
	35,  // 221: core.BackupService.Get:output_type -> api.Response
	35,  // 222: core.BackupService.Delete:output_type -> api.Response
	35,  // 223: core.BackupService.Update:output_type -> api.Response
	35,  // 224: core.BackupService.Import:output_type -> api.Response
	35,  // 225: core.BackupService.Export:output_type -> api.Response
	35,  // 226: core.BackupService.Upload:output_type -> api.Response
	22,  // 227: core.BackupService.Download:output_type -> core.DownloadFileResponse
	35,  // 228: core.TaskManagerService.Query:output_type -> api.Response
	35,  // 229: core.TaskManagerService.Get:output_type -> api.Response
	35,  // 230: core.TaskManagerService.Delete:output_type -> api.Response
	35,  // 231: core.TaskManagerService.Update:output_type -> api.Response
	35,  // 232: core.TaskManagerService.Replace:output_type -> api.Response
	35,  // 233: core.TaskManagerService.Create:output_type -> api.Response
	35,  // 234: core.MediaLibraryService.Query:output_type -> api.Response
	35,  // 235: core.MediaLibraryService.UploadFromUrl:output_type -> api.Response
	35,  // 236: core.MediaLibraryService.UploadFromBase64:output_type -> api.Response
	35,  // 237: core.MediaLibraryService.Mkdir:output_type -> api.Response
	35,  // 238: core.MediaLibraryService.DeleteFiles:output_type -> api.Response
	35,  // 239: core.MediaLibraryDirSettingService.Create:output_type -> api.Response
	35,  // 240: core.MediaLibraryDirSettingService.Delete:output_type -> api.Response
	35,  // 241: core.MediaLibraryDirSettingService.Update:output_type -> api.Response
	35,  // 242: core.MediaLibraryDirSettingService.Replace:output_type -> api.Response
	35,  // 243: core.MediaLibraryDirSettingService.Get:output_type -> api.Response
	35,  // 244: core.MediaLibraryDirSettingService.GetByPath:output_type -> api.Response
	35,  // 245: core.MediaLibraryDirSettingService.Query:output_type -> api.Response
	3,   // 246: core.AuthorizationService.CheckPermission:output_type -> core.AuthorizationDecision
	7,   // 247: core.AuthorizationService.BatchCheckResourceAccess:output_type -> core.BatchResourceAccessResponse
	9,   // 248: core.AuthorizationService.ListAccessibleResources:output_type -> core.ListAccessibleResourcesResponse
	1,   // 249: core.AuthorizationService.GetAuthorizationRevision:output_type -> core.AuthorizationRevisionResponse
	127, // [127:250] is the sub-list for method output_type
	4,   // [4:127] is the sub-list for method input_type
	4,   // [4:4] is the sub-list for extension type_name
	4,   // [4:4] is the sub-list for extension extendee
	0,   // [0:4] is the sub-list for field type_name
}

func init() { file_core_core_proto_init() }
func file_core_core_proto_init() {
	if File_core_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_core_proto_rawDesc), len(file_core_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   21,
		},
		GoTypes:           file_core_core_proto_goTypes,
		DependencyIndexes: file_core_core_proto_depIdxs,
		MessageInfos:      file_core_core_proto_msgTypes,
	}.Build()
	File_core_core_proto = out.File
	file_core_core_proto_goTypes = nil
	file_core_core_proto_depIdxs = nil
}
