// Copyright 2015 The gRPC Authors

// protoc -I ./ --go_out=. ./ai/ai.proto
// protoc -I ./ --go-grpc_out=. ai/ai.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: ai/ai.proto

package ai

import (
	context "context"
	api "github.com/air-iot/api-client-go/v4/api"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BigModelService_Call_FullMethodName = "/ai.BigModelService/Call"
)

// BigModelServiceClient is the client API for BigModelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BigModelServiceClient interface {
	Call(ctx context.Context, in *api.CreateRequest, opts ...grpc.CallOption) (*api.Response, error)
}

type bigModelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBigModelServiceClient(cc grpc.ClientConnInterface) BigModelServiceClient {
	return &bigModelServiceClient{cc}
}

func (c *bigModelServiceClient) Call(ctx context.Context, in *api.CreateRequest, opts ...grpc.CallOption) (*api.Response, error) {
	out := new(api.Response)
	err := c.cc.Invoke(ctx, BigModelService_Call_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BigModelServiceServer is the server API for BigModelService service.
// All implementations must embed UnimplementedBigModelServiceServer
// for forward compatibility
type BigModelServiceServer interface {
	Call(context.Context, *api.CreateRequest) (*api.Response, error)
	mustEmbedUnimplementedBigModelServiceServer()
}

// UnimplementedBigModelServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBigModelServiceServer struct {
}

func (UnimplementedBigModelServiceServer) Call(context.Context, *api.CreateRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedBigModelServiceServer) mustEmbedUnimplementedBigModelServiceServer() {}

// UnsafeBigModelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BigModelServiceServer will
// result in compilation errors.
type UnsafeBigModelServiceServer interface {
	mustEmbedUnimplementedBigModelServiceServer()
}

func RegisterBigModelServiceServer(s grpc.ServiceRegistrar, srv BigModelServiceServer) {
	s.RegisterService(&BigModelService_ServiceDesc, srv)
}

func _BigModelService_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BigModelServiceServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BigModelService_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BigModelServiceServer).Call(ctx, req.(*api.CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BigModelService_ServiceDesc is the grpc.ServiceDesc for BigModelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BigModelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.BigModelService",
	HandlerType: (*BigModelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _BigModelService_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai/ai.proto",
}
